package com.example.yourappname

data class Flashcard(
    val japanese: String,
    val meaning: String
)

data class FlashcardSet(
    val id: String, // e.g., "minna_L1"
    val title: String, // e.g., "Lesson 1"
    val cards: List<Flashcard>
)

fun getAllFlashcardSets(): List<FlashcardSet> {
    return (1..25).map { lessonNumber ->
        FlashcardSet(
            id = "minna_L$lessonNumber",
            title = "L - $lessonNumber",
            cards = when (lessonNumber) {
                1 -> listOf(
                    Flashcard("わたし", "I"),
                    Flashcard("わたしたち", "we"),
                    Flashcard("あなた", "you"),
                    Flashcard("あのひと", "that person, he, she"),
                    Flashcard("あのかた", "that person, he, she (more polite)"),
                    Flashcard("みなさん", "ladies and gentlemen, all of you, everyone"),
                    Flashcard("～さん", "Mr./Ms."),
                    Flashcard("～ちゃん", "suffix for child's name"),
                    Flashcard("～くん", "suffix for boy's name"),
                    Flashcard("～じん", "suffix for nationality"),
                    Flashcard("せんせい", "teacher"),
                    Flashcard("きょうし", "teacher (job)"),
                    Flashcard("がくせい", "student"),
                    Flashcard("かいしゃいん", "company employee"),
                    Flashcard("しゃいん", "employee of ~ company"),
                    Flashcard("ぎんこういん", "bank employee"),
                    Flashcard("いしゃ", "medical doctor"),
                    Flashcard("けんきゅうしゃ", "researcher, scholar"),
                    Flashcard("エンジニア", "engineer"),
                    Flashcard("だいがく", "university"),
                    Flashcard("びょういん", "hospital"),
                    Flashcard("でんき", "electricity, light"),
                    Flashcard("だれ", "who"),
                    Flashcard("どなた", "who (polite)"),
                    Flashcard("～さい", "~years old"),
                    Flashcard("なんさい", "how old"),
                    Flashcard("おいくつ", "how old (polite)"),
                    Flashcard("はい", "yes"),
                    Flashcard("いいえ", "no"),
                    Flashcard("しつれいですが", "Excuse me, but"),
                    Flashcard("おなまえは？", "May I have your name?"),
                    Flashcard("はじめまして", "How do you do?"),
                    Flashcard("どうぞ よろしく おねがいします", "Nice to meet you."),
                    Flashcard("こちらは ～さん です", "This is Mr./Ms. ~."),
                    Flashcard("～から きました", "I came from ~."),
                    Flashcard("アメリカ", "U.S.A"),
                    Flashcard("イギリス", "U.K."),
                    Flashcard("インド", "India"),
                    Flashcard("インドネシア", "Indonesia"),
                    Flashcard("かんこく", "South Korea"),
                    Flashcard("タイ", "Thailand"),
                    Flashcard("ちゅうごく", "China"),
                    Flashcard("ドイツ", "Germany"),
                    Flashcard("にほん", "Japan"),
                    Flashcard("フランス", "France"),
                    Flashcard("ブラジル", "Brazil")
                )
                2 -> listOf(
                    Flashcard("これ", "this (thing here)"),
                    Flashcard("それ", "that (thing near you)"),
                    Flashcard("あれ", "that (thing over there)"),
                    Flashcard("この～", "this ~, this ~ here"),
                    Flashcard("その～", "that ~, that ~ there"),
                    Flashcard("あの～", "that ~, that ~ over there"),
                    Flashcard("本 (ほん)", "book"),
                    Flashcard("辞書 (じしょ)", "dictionary"),
                    Flashcard("雑誌 (ざっし)", "magazine"),
                    Flashcard("新聞 (しんぶん)", "newspaper"),
                    Flashcard("ノート", "notebook"),
                    Flashcard("手帳 (てちょう)", "pocket notebook"),
                    Flashcard("名刺 (めいし)", "business card"),
                    Flashcard("カード", "card"),
                    Flashcard("鉛筆 (えんぴつ)", "pencil"),
                    Flashcard("ボールペン", "ballpoint pen"),
                    Flashcard("シャープペンシル", "mechanical pencil"),
                    Flashcard("かぎ", "key"),
                    Flashcard("時計 (とけい)", "watch, clock"),
                    Flashcard("傘 (かさ)", "umbrella"),
                    Flashcard("かばん", "bag, briefcase"),
                    Flashcard("テレビ", "television"),
                    Flashcard("ラジオ", "radio"),
                    Flashcard("カメラ", "camera"),
                    Flashcard("コンピューター", "computer"),
                    Flashcard("自動車 (じどうしゃ)", "automobile, car"),
                    Flashcard("机 (つくえ)", "desk"),
                    Flashcard("いす", "chair"),
                    Flashcard("チョコレート", "chocolate"),
                    Flashcard("コーヒー", "coffee"),
                    Flashcard("英語 (えいご)", "the English language"),
                    Flashcard("日本語 (にほんご)", "the Japanese language"),
                    Flashcard("～語 (～ご)", "~ language"),
                    Flashcard("何 (なん)", "what"),
                    Flashcard("そう", "so"),
                    Flashcard("ちがいます", "No it isn't / You are wrong."),
                    Flashcard("そうですか", "I see / Is that so?"),
                    Flashcard("あのう", "well... (used to show hesitation)"),
                    Flashcard("ほんのきもちです", "It's a token of my gratitude."),
                    Flashcard("どうぞ", "Please / Here you are."),
                    Flashcard("どうも", "Well, thanks."),
                    Flashcard("ありがとう ございます", "Thank you very much."),
                    Flashcard("これからおせわになります", "I hope for your kind assistance hereafter."),
                    Flashcard("こちらこそよろしく", "I am pleased to meet you, too.")
                )
                3 -> listOf(
                    Flashcard("ここ", "here, this place"),
                    Flashcard("そこ", "there, that place near you"),
                    Flashcard("あそこ", "that place over there"),
                    Flashcard("どこ", "where, what place?"),
                    Flashcard("こちら", "this way, this place (polite)"),
                    Flashcard("そちら", "that way, that place near you (polite)"),
                    Flashcard("あちら", "that way, that place over there (polite)"),
                    Flashcard("どちら", "which way, where (polite)"),
                    Flashcard("きょうしつ", "classroom"),
                    Flashcard("しょくどう", "dining hall, canteen"),
                    Flashcard("じむしょ", "office"),
                    Flashcard("かいぎしつ", "meeting room"),
                    Flashcard("うけつけ", "reception desk"),
                    Flashcard("ロビー", "lobby"),
                    Flashcard("へや", "room"),
                    Flashcard("トイレ / おてあらい", "toilet, restroom"),
                    Flashcard("かいだん", "staircase"),
                    Flashcard("エレベーター", "elevator, lift"),
                    Flashcard("エスカレーター", "escalator"),
                    Flashcard("[お]くに", "country"),
                    Flashcard("かいしゃ", "company"),
                    Flashcard("うち / いえ", "house, home"),
                    Flashcard("でんわ", "telephone, phone call"),
                    Flashcard("くつ", "shoes"),
                    Flashcard("ネクタイ", "necktie"),
                    Flashcard("ワイン", "wine"),
                    Flashcard("うりば", "department, counter (in a department store)"),
                    Flashcard("ちか", "basement"),
                    Flashcard("～かい", "-th floor"),
                    Flashcard("なんがい", "what floor"),
                    Flashcard("～えん", "yen"),
                    Flashcard("いくら", "how much"),
                    Flashcard("ひゃく", "hundred"),
                    Flashcard("せん", "thousand"),
                    Flashcard("まん", "ten thousand"),
                    Flashcard("すみません", "Excuse me."),
                    Flashcard("～でございます", "(polite equivalent of です)"),
                    Flashcard("～をみせてください", "Please show me [~]."),
                    Flashcard("じゃ", "well, then, in that case"),
                    Flashcard("～をください", "Give me [~], please.")
                )
                4 -> listOf(
                    Flashcard("おきます", "get up, wake up"),
                    Flashcard("ねます", "sleep, go to bed"),
                    Flashcard("はたらきます", "work"),
                    Flashcard("やすみます", "take a rest, take a holiday"),
                    Flashcard("べんきょうします", "study"),
                    Flashcard("おわります", "finish"),
                    Flashcard("デパート", "department store"),
                    Flashcard("ぎんこう", "bank"),
                    Flashcard("ゆうびんきょく", "post office"),
                    Flashcard("としょかん", "library"),
                    Flashcard("びじゅつかん", "art museum"),
                    Flashcard("いま", "now"),
                    Flashcard("～じ", "~ o'clock"),
                    Flashcard("～ふん / ～ぷん", "~ minute(s)"),
                    Flashcard("はん", "half"),
                    Flashcard("なんじ", "what time"),
                    Flashcard("なんぷん", "what minute"),
                    Flashcard("ごぜん", "a.m., morning"),
                    Flashcard("ごご", "p.m., afternoon"),
                    Flashcard("あさ", "morning"),
                    Flashcard("ひる", "daytime, noon"),
                    Flashcard("ばん / よる", "night, evening"),
                    Flashcard("おととい", "the day before yesterday"),
                    Flashcard("きのう", "yesterday"),
                    Flashcard("きょう", "today"),
                    Flashcard("あした", "tomorrow"),
                    Flashcard("あさって", "the day after tomorrow"),
                    Flashcard("けさ", "this morning"),
                    Flashcard("こんばん", "this evening, tonight"),
                    Flashcard("やすみ", "rest, a holiday, a day off"),
                    Flashcard("ひるやすみ", "lunch break"),
                    Flashcard("まいあさ", "every morning"),
                    Flashcard("まいばん", "every night"),
                    Flashcard("まいにち", "every day"),
                    Flashcard("げつようび", "Monday"),
                    Flashcard("かようび", "Tuesday"),
                    Flashcard("すいようび", "Wednesday"),
                    Flashcard("もくようび", "Thursday"),
                    Flashcard("きんようび", "Friday"),
                    Flashcard("どようび", "Saturday"),
                    Flashcard("にちようび", "Sunday"),
                    Flashcard("なんようび", "what day of the week"),
                    Flashcard("ばんごう", "number"),
                    Flashcard("なんばん", "what number"),
                    Flashcard("～から", "from ~"),
                    Flashcard("～まで", "up to, until ~"),
                    Flashcard("～と～", "and ~ (used to connect nouns)"),
                    Flashcard("たいへんですね", "That’s tough, isn’t it?"),
                    Flashcard("えーと", "well, let me see..."),
                    Flashcard("おねがいします", "Please (ask for a favor)"),
                    Flashcard("かしこまりました", "Certainly (sir, madam)."),
                    Flashcard("おといあわせのばんごう", "the number being inquired about"),
                    Flashcard("どうもありがとうございました", "Thank you very much")
                )
                5 -> listOf(
                    Flashcard("いきます", "go"),
                    Flashcard("きます", "come"),
                    Flashcard("かえります", "return (home)"),
                    Flashcard("がっこう", "school"),
                    Flashcard("スーパー", "supermarket"),
                    Flashcard("えき", "station"),
                    Flashcard("ひこうき", "airplane"),
                    Flashcard("ふね", "ship"),
                    Flashcard("でんしゃ", "electric train"),
                    Flashcard("ちかてつ", "subway, underground"),
                    Flashcard("しんかんせん", "the Shinkansen, bullet train"),
                    Flashcard("バス", "bus"),
                    Flashcard("タクシー", "taxi"),
                    Flashcard("じてんしゃ", "bicycle"),
                    Flashcard("あるいて", "on foot"),
                    Flashcard("ひと", "person, people"),
                    Flashcard("ともだち", "friend"),
                    Flashcard("かれ", "he, boyfriend, lover"),
                    Flashcard("かのじょ", "she, girlfriend, lover"),
                    Flashcard("かぞく", "family"),
                    Flashcard("ひとりで", "alone, by oneself"),
                    Flashcard("せんしゅう", "last week"),
                    Flashcard("こんしゅう", "this week"),
                    Flashcard("らいしゅう", "next week"),
                    Flashcard("せんげつ", "last month"),
                    Flashcard("こんげつ", "this month"),
                    Flashcard("らいげつ", "next month"),
                    Flashcard("きょねん", "last year"),
                    Flashcard("ことし", "this year"),
                    Flashcard("らいねん", "next year"),
                    Flashcard("～がつ", "~th month of the year"),
                    Flashcard("なんがつ", "what month"),
                    Flashcard("ついたち", "first day of the month"),
                    Flashcard("ふつか", "second, two days"),
                    Flashcard("みっか", "third, three days"),
                    Flashcard("よっか", "fourth, four days"),
                    Flashcard("いつか", "fifth, five days"),
                    Flashcard("むいか", "sixth, six days"),
                    Flashcard("なのか", "seventh, seven days"),
                    Flashcard("ようか", "eighth, eight days"),
                    Flashcard("ここのか", "ninth, nine days"),
                    Flashcard("とおか", "tenth, ten days"),
                    Flashcard("じゅうよっか", "fourteenth, fourteen days"),
                    Flashcard("はつか", "twentieth, twenty days"),
                    Flashcard("にじゅうよっか", "twenty-fourth, twenty-four days"),
                    Flashcard("～にち", "~th day of the month, ~ days"),
                    Flashcard("なんにち", "which day of the month, how many days"),
                    Flashcard("いつ", "when"),
                    Flashcard("たんじょうび", "birthday"),
                    Flashcard("ふつう", "local (train)"),
                    Flashcard("きゅうこう", "rapid"),
                    Flashcard("とっきゅう", "express"),
                    Flashcard("つぎの", "next"),
                    Flashcard("どういたしまして", "You're welcome. /Don't mention it."),
                    Flashcard("～ばんせん", "platform ~, ~th platform")
                )
                6 -> listOf(
                    Flashcard("たべます", "eat"),
                    Flashcard("のみます", "drink"),
                    Flashcard("すいます [たばこを～]", "smoke [a cigarette]"),
                    Flashcard("みます", "see, look at, watch"),
                    Flashcard("ききます", "hear, listen"),
                    Flashcard("よみます", "read"),
                    Flashcard("かきます", "write, draw, paint"),
                    Flashcard("かいます", "buy"),
                    Flashcard("とります [しゃしんを～]", "take [a photograph]"),
                    Flashcard("します", "do, play"),
                    Flashcard("あいます [ともだちに～]", "meet [a friend]"),
                    Flashcard("ごはん", "a meal, cooked rice"),
                    Flashcard("あさごはん", "breakfast"),
                    Flashcard("ひるごはん", "lunch"),
                    Flashcard("ばんごはん", "supper"),
                    Flashcard("パン", "bread"),
                    Flashcard("たまご", "egg"),
                    Flashcard("にく", "meat"),
                    Flashcard("さかな", "fish"),
                    Flashcard("やさい", "vegetable"),
                    Flashcard("くだもの", "fruit"),
                    Flashcard("みず", "water"),
                    Flashcard("おちゃ", "tea, green tea"),
                    Flashcard("こうちゃ", "black tea"),
                    Flashcard("ぎゅうにゅう / ミルク", "milk"),
                    Flashcard("ジュース", "juice"),
                    Flashcard("ビール", "beer"),
                    Flashcard("おさけ", "alcohol, Japanese rice wine"),
                    Flashcard("ビデオ", "video"),
                    Flashcard("えいが", "movie"),
                    Flashcard("てがみ", "letter"),
                    Flashcard("レポート", "report"),
                    Flashcard("しゃしん", "photograph"),
                    Flashcard("みせ", "store, shop"),
                    Flashcard("レストラン", "restaurant"),
                    Flashcard("にわ", "garden"),
                    Flashcard("しゅくだい", "homework"),
                    Flashcard("テニス", "tennis"),
                    Flashcard("サッカー", "soccer, football"),
                    Flashcard("おはなみ", "cherry-blossom viewing"),
                    Flashcard("なに", "what"),
                    Flashcard("いっしょに", "together"),
                    Flashcard("ちょっと", "a little while, a little bit"),
                    Flashcard("いつも", "always, usually"),
                    Flashcard("ときどき", "sometimes"),
                    Flashcard("それから", "after that, and then"),
                    Flashcard("ええ", "yes"),
                    Flashcard("いいですね", "That's good."),
                    Flashcard("わかりました", "I see."),
                    Flashcard("なんですか", "Yes?"),
                    Flashcard("じゃ、また", "See you [tommorow].")
                )
                7 -> listOf(
                    Flashcard("きります", "cut, slice"),
                    Flashcard("おくります", "send"),
                    Flashcard("あげます", "give"),
                    Flashcard("もらいます", "receive"),
                    Flashcard("かします", "lend"),
                    Flashcard("かります", "borrow"),
                    Flashcard("おしえます", "teach"),
                    Flashcard("ならいます", "learn"),
                    Flashcard("かけます [でんわを～]", "make [a telephone call]"),
                    Flashcard("て", "hand, arm"),
                    Flashcard("はし", "chopsticks"),
                    Flashcard("スプーン", "spoon"),
                    Flashcard("ナイフ", "knife"),
                    Flashcard("フォーク", "fork"),
                    Flashcard("はさみ", "scissors"),
                    Flashcard("ファクス", "fax"),
                    Flashcard("ワープロ", "word processor"),
                    Flashcard("パソコン", "personal computer"),
                    Flashcard("パンチ", "punch"),
                    Flashcard("ホッチキス", "stapler"),
                    Flashcard("セロテープ", "Scotch tape, clear adhesive tape"),
                    Flashcard("けしゴム", "eraser"),
                    Flashcard("かみ", "paper"),
                    Flashcard("はな", "flower, blossom"),
                    Flashcard("シャツ", "shirt"),
                    Flashcard("プレゼント", "present, gift"),
                    Flashcard("にもつ", "baggage, parcel"),
                    Flashcard("おかね", "money"),
                    Flashcard("きっぷ", "ticket"),
                    Flashcard("クリスマス", "Christmas"),
                    Flashcard("ちち", "(my) father"),
                    Flashcard("はは", "(my) mother"),
                    Flashcard("おとうさん", "(someone else's) father"),
                    Flashcard("おかあさん", "(someone else's) mother"),
                    Flashcard("もう", "already"),
                    Flashcard("まだ", "not yet"),
                    Flashcard("これから", "from now on, soon"),
                    Flashcard("～、すてきですね", "What a nice [~]!"),
                    Flashcard("ごめんください", "Excuse me. /Anybody home? /May I come in?"),
                    Flashcard("いらっしゃい", "Welcome."),
                    Flashcard("どうぞ おあがりください", "Do come in."),
                    Flashcard("しつれいします", "May I? (lit. I'm afraid I'll be disturbing you.)"),
                    Flashcard("～は いかがですか", "Won't you have ~? /Would you like to have ~?"),
                    Flashcard("いただきます", "Thank you. /I accept. (said before starting to eat or drink)"),
                    Flashcard("りょこう", "travel, trip"),
                    Flashcard("おみやげ", "souvenir, present")
                )
                8 -> listOf(
                    Flashcard("ハンサム[な]", "handsome"),
                    Flashcard("きれい[な]", "beautiful, clean"),
                    Flashcard("しずか[な]", "quiet"),
                    Flashcard("にぎやか[な]", "lively"),
                    Flashcard("ゆうめい[な]", "famous"),
                    Flashcard("しんせつ[な]", "kind"),
                    Flashcard("げんき[な]", "healthy, sound, cheerful"),
                    Flashcard("ひま[な]", "free (time)"),
                    Flashcard("べんり[な]", "convenient"),
                    Flashcard("すてき[な]", "fine, nice, wonderful"),
                    Flashcard("おおきい", "big, large"),
                    Flashcard("ちいさい", "small, little"),
                    Flashcard("あたらしい", "new"),
                    Flashcard("ふるい", "old (not of age)"),
                    Flashcard("いい (よい)", "good"),
                    Flashcard("わるい", "bad"),
                    Flashcard("あつい", "hot"),
                    Flashcard("さむい", "cold (weather)"),
                    Flashcard("つめたい", "cold (to the touch)"),
                    Flashcard("むずかしい", "difficult"),
                    Flashcard("やさしい", "easy"),
                    Flashcard("たかい", "expensive, tall, high"),
                    Flashcard("やすい", "inexpensive"),
                    Flashcard("ひくい", "low"),
                    Flashcard("おもしろい", "interesting"),
                    Flashcard("おいしい", "delicious, tasty"),
                    Flashcard("いそがしい", "busy"),
                    Flashcard("たのしい", "enjoyable"),
                    Flashcard("しろい", "white"),
                    Flashcard("くろい", "black"),
                    Flashcard("あかい", "red"),
                    Flashcard("あおい", "blue"),
                    Flashcard("さくら", "cherry (blossom)"),
                    Flashcard("やま", "mountain"),
                    Flashcard("まち", "town, city"),
                    Flashcard("たべもの", "food"),
                    Flashcard("くるま", "car, vehicle"),
                    Flashcard("ところ", "place"),
                    Flashcard("りょう", "dormitory"),
                    Flashcard("べんきょう", "study"),
                    Flashcard("せいかつ", "life"),
                    Flashcard("[お]しごと", "work, business"),
                    Flashcard("どう", "how"),
                    Flashcard("どんな～", "what kind of ~"),
                    Flashcard("どれ", "which one (of three or more)"),
                    Flashcard("とても", "very"),
                    Flashcard("あまり", "not so (used with negatives)"),
                    Flashcard("そして", "and (used to connect sentences)"),
                    Flashcard("～が、～", "~, but ~"),
                    Flashcard("おげんきですか", "How are you?"),
                    Flashcard("そうですね", "Well, let me see. (pausing)"),
                    Flashcard("にほんのせいかつになれましたか", "Have you got used to life in Japan?"),
                    Flashcard("～、もういっぱいいかがですか", "Won't you have another cup of [~]?"),
                    Flashcard("いいえ、けっこうです", "No, thank you."),
                    Flashcard("そろそろしつれいします", "It's almost time to leave now."),
                    Flashcard("またいらっしゃってください", "Please come again.")
                )
                9 -> listOf(
                    Flashcard("わかります", "understand"),
                    Flashcard("あります", "have"),
                    Flashcard("すき[な]", "like"),
                    Flashcard("きらい[な]", "dislike"),
                    Flashcard("じょうず[な]", "good at"),
                    Flashcard("へた[な]", "poor at"),
                    Flashcard("りょうり", "dish (cooked food), cooking"),
                    Flashcard("のみもの", "drinks"),
                    Flashcard("スポーツ", "sports"),
                    Flashcard("やきゅう", "baseball"),
                    Flashcard("ダンス", "dance"),
                    Flashcard("おんがく", "music"),
                    Flashcard("うた", "song"),
                    Flashcard("クラシック", "classical music"),
                    Flashcard("ジャズ", "jazz"),
                    Flashcard("コンサート", "concert"),
                    Flashcard("カラオケ", "karaoke"),
                    Flashcard("かぶき", "Kabuki"),
                    Flashcard("え", "picture, drawing"),
                    Flashcard("じ", "letter, character"),
                    Flashcard("かんじ", "Chinese characters"),
                    Flashcard("ひらがな", "Hiragana script"),
                    Flashcard("かたかな", "Katakana script"),
                    Flashcard("ローマじ", "the Roman alphabet"),
                    Flashcard("こまかいおかね", "small change"),
                    Flashcard("チケット", "ticket"),
                    Flashcard("じかん", "time"),
                    Flashcard("ようじ", "something to do, errand"),
                    Flashcard("やくそく", "promise, appointment"),
                    Flashcard("ごしゅじん", "(someone else's) husband"),
                    Flashcard("おっと / しゅじん", "(my) husband"),
                    Flashcard("おくさん", "(someone else's) wife"),
                    Flashcard("つま / かない", "(my) wife"),
                    Flashcard("こども", "child"),
                    Flashcard("よく", "well, much"),
                    Flashcard("だいたい", "mostly, roughly"),
                    Flashcard("たくさん", "many, much"),
                    Flashcard("すこし", "a little, a few"),
                    Flashcard("ぜんぜん", "not at all (used with negatives)"),
                    Flashcard("はやく", "early, quickly, fast"),
                    Flashcard("～から", "because ~"),
                    Flashcard("どうして", "why"),
                    Flashcard("ざんねんですね", "I'm sorry to hear that. /That's a pity."),
                    Flashcard("もしもし", "hello (on the phone)"),
                    Flashcard("ああ", "oh"),
                    Flashcard("いっしょに いかがですか", "Won't you join me/us?"),
                    Flashcard("～は ちょっと…", "[~] is a bit difficult. (a euphemism used to decline an invitation)"),
                    Flashcard("だめですか", "So you cannot (come)?"),
                    Flashcard("またこんどおねがいします", "Please ask me again some other time.")
                )
                10 -> listOf(
                    Flashcard("います", "exist, be (animate)"),
                    Flashcard("あります", "exist, be (inanimate)"),
                    Flashcard("いろいろ[な]", "various"),
                    Flashcard("おとこのひと", "man"),
                    Flashcard("おんなのひと", "woman"),
                    Flashcard("おとこのこ", "boy"),
                    Flashcard("おんなのこ", "girl"),
                    Flashcard("いぬ", "dog"),
                    Flashcard("ねこ", "cat"),
                    Flashcard("き", "tree, wood"),
                    Flashcard("もの", "thing"),
                    Flashcard("フィルム", "film"),
                    Flashcard("でんち", "battery"),
                    Flashcard("はこ", "box"),
                    Flashcard("スイッチ", "switch"),
                    Flashcard("れいぞうこ", "refrigerator"),
                    Flashcard("テーブル", "table"),
                    Flashcard("ベッド", "bed"),
                    Flashcard("たな", "shelf"),
                    Flashcard("ドア", "door"),
                    Flashcard("まど", "window"),
                    Flashcard("ポスト", "postbox, mailbox"),
                    Flashcard("ビル", "building"),
                    Flashcard("こうえん", "park"),
                    Flashcard("きっさてん", "cafe, coffee shop"),
                    Flashcard("ほんや", "bookstore"),
                    Flashcard("～や", "~ shop, ~ store"),
                    Flashcard("のりば", "a fixed place to catch taxis, trains, etc."),
                    Flashcard("けん", "prefecture"),
                    Flashcard("うえ", "on, above, over"),
                    Flashcard("した", "under, below, beneath"),
                    Flashcard("まえ", "front, before"),
                    Flashcard("うしろ", "back, behind"),
                    Flashcard("みぎ", "right (side)"),
                    Flashcard("ひだり", "left (side)"),
                    Flashcard("なか", "in, inside, middle"),
                    Flashcard("そと", "outside"),
                    Flashcard("となり", "next, next door"),
                    Flashcard("ちかく", "near, vicinity"),
                    Flashcard("あいだ", "between, among"),
                    Flashcard("～や～[など]", "~, ~, and so on"),
                    Flashcard("いちばん～", "the most ~"),
                    Flashcard("～だんめ", "the ~th shelf"),
                    Flashcard("どうもすみません", "Thank you.")
                )
                11 -> listOf(
                    Flashcard("[こどもが] います", "have [a child]"),
                    Flashcard("[にほんに] います", "stay, be [in Japan]"),
                    Flashcard("かかります", "take (referring to time or money)"),
                    Flashcard("[かいしゃを] やすみます", "take a day off [from work]"),
                    Flashcard("ひとつ", "one (thing)"),
                    Flashcard("ふたつ", "two (things)"),
                    Flashcard("みっつ", "three (things)"),
                    Flashcard("よっつ", "four (things)"),
                    Flashcard("いつつ", "five (things)"),
                    Flashcard("むっつ", "six (things)"),
                    Flashcard("ななつ", "seven (things)"),
                    Flashcard("やっつ", "eight (things)"),
                    Flashcard("ここのつ", "nine (things)"),
                    Flashcard("とお", "ten (things)"),
                    Flashcard("いくつ", "how many"),
                    Flashcard("ひとり", "one person"),
                    Flashcard("ふたり", "two people"),
                    Flashcard("～にん", "~ people"),
                    Flashcard("～だい", "(counter for machines, cars, etc.)"),
                    Flashcard("～まい", "(counter for paper, stamps, etc.)"),
                    Flashcard("～かい", "~ times"),
                    Flashcard("りんご", "apple"),
                    Flashcard("みかん", "mandarin orange"),
                    Flashcard("サンドイッチ", "sandwich"),
                    Flashcard("カレー[ライス]", "curry [and rice]"),
                    Flashcard("アイスクリーム", "ice cream"),
                    Flashcard("きって", "postage stamp"),
                    Flashcard("はがき", "postcard"),
                    Flashcard("ふうとう", "envelope"),
                    Flashcard("りょうしん", "parents"),
                    Flashcard("きょうだい", "brothers and sisters"),
                    Flashcard("あに", "(my) elder brother"),
                    Flashcard("おにいさん", "(someone else's) elder brother"),
                    Flashcard("あね", "(my) elder sister"),
                    Flashcard("おねえさん", "(someone else's) elder sister"),
                    Flashcard("おとうと", "(my) younger brother"),
                    Flashcard("おとうとさん", "(someone else's) younger brother"),
                    Flashcard("いもうと", "(my) younger sister"),
                    Flashcard("いもうとさん", "(someone else's) younger sister"),
                    Flashcard("がいこく", "foreign country"),
                    Flashcard("～じかん", "~ hours"),
                    Flashcard("～しゅうかん", "~ weeks"),
                    Flashcard("～かげつ", "~ months"),
                    Flashcard("～ねん", "~ years"),
                    Flashcard("～ぐらい", "about ~"),
                    Flashcard("どのくらい", "how long"),
                    Flashcard("ぜんぶで", "in total"),
                    Flashcard("みんな", "all, everyone"),
                    Flashcard("～だけ", "only ~"),
                    Flashcard("いらっしゃいませ", "Welcome. / May I help you?"),
                    Flashcard("いいおてんきですね", "Nice weather, isn't it?"),
                    Flashcard("おでかけですか", "Are you going out?"),
                    Flashcard("ちょっと～まで", "I'm just going to ~."),
                    Flashcard("いっていらっしゃい", "So long. (Go and come back.)"),
                    Flashcard("いってまいります", "So long. (I'm going and coming back.)"),
                    Flashcard("ふなびん", "sea mail"),
                    Flashcard("こうくうびん / エヤメール", "airmail"),
                    Flashcard("おねがいします", "please")
                )
                12 -> listOf(
                    Flashcard("かんたん[な]", "easy, simple"),
                    Flashcard("ちかい", "near"),
                    Flashcard("とおい", "far"),
                    Flashcard("はやい", "fast, early"),
                    Flashcard("おそい", "slow, late"),
                    Flashcard("おおい [ひとが～]", "many [people]"),
                    Flashcard("すくない [ひとが～]", "few [people]"),
                    Flashcard("あたたかい", "warm"),
                    Flashcard("すずしい", "cool"),
                    Flashcard("あまい", "sweet"),
                    Flashcard("からい", "hot, spicy"),
                    Flashcard("おもい", "heavy"),
                    Flashcard("かるい", "light"),
                    Flashcard("いい [コーヒーが～]", "prefer [coffee]"),
                    Flashcard("きせつ", "season"),
                    Flashcard("はる", "spring"),
                    Flashcard("なつ", "summer"),
                    Flashcard("あき", "autumn, fall"),
                    Flashcard("ふゆ", "winter"),
                    Flashcard("てんき", "weather"),
                    Flashcard("あめ", "rain, rainy"),
                    Flashcard("ゆき", "snow, snowy"),
                    Flashcard("くもり", "cloudy"),
                    Flashcard("ホテル", "hotel"),
                    Flashcard("くうこう", "airport"),
                    Flashcard("うみ", "sea, ocean"),
                    Flashcard("せかい", "world"),
                    Flashcard("パーティー", "party"),
                    Flashcard("おまつり", "festival"),
                    Flashcard("しけん", "examination"),
                    Flashcard("すきやき", "sukiyaki"),
                    Flashcard("さしみ", "sashimi"),
                    Flashcard("おすし", "sushi"),
                    Flashcard("てんぷら", "tempura"),
                    Flashcard("いけばな", "flower arrangement"),
                    Flashcard("もみじ", "maple, red leaves of autumn"),
                    Flashcard("どちら", "which one (of two)"),
                    Flashcard("どちらも", "both"),
                    Flashcard("ずっと", "by far"),
                    Flashcard("はじめて", "for the first time"),
                    Flashcard("ただいま", "I'm home."),
                    Flashcard("おかえりなさい", "Welcome home."),
                    Flashcard("すごいですね", "That's amazing!"),
                    Flashcard("でも", "but"),
                    Flashcard("つかれました", "I'm tired.")
                )
                13 -> listOf(
                    Flashcard("あそびます", "enjoy oneself, play"),
                    Flashcard("およぎます", "swim"),
                    Flashcard("むかえます", "go to meet, welcome"),
                    Flashcard("つかれます", "get tired"),
                    Flashcard("だします [てがみを～]", "send [a letter]"),
                    Flashcard("はいります [きっさてんに～]", "enter [a coffee shop]"),
                    Flashcard("でます [きっさてんを～]", "go out of [a coffee shop]"),
                    Flashcard("けっこんします", "marry, get married"),
                    Flashcard("かいものします", "do shopping"),
                    Flashcard("しょくじします", "have a meal, dine"),
                    Flashcard("さんぽします [こうえんを～]", "take a walk [in a park]"),
                    Flashcard("たいへん[な]", "hard, tough, severe, awful"),
                    Flashcard("ほしい", "want (something)"),
                    Flashcard("さびしい", "lonely"),
                    Flashcard("ひろい", "wide, spacious"),
                    Flashcard("せまい", "narrow, small (room)"),
                    Flashcard("しやくしょ", "municipal office, city hall"),
                    Flashcard("プール", "swimming pool"),
                    Flashcard("かわ", "river"),
                    Flashcard("けいざい", "economy"),
                    Flashcard("びじゅつ", "fine arts"),
                    Flashcard("つり", "fishing"),
                    Flashcard("スキー", "skiing"),
                    Flashcard("かいぎ", "meeting, conference"),
                    Flashcard("とうろく", "registration"),
                    Flashcard("しゅうまつ", "weekend"),
                    Flashcard("～ごろ", "about (time)"),
                    Flashcard("なにか", "something"),
                    Flashcard("どこか", "somewhere, some place"),
                    Flashcard("おなかが すきました", "I'm hungry."),
                    Flashcard("おなかが いっぱいです", "I'm full."),
                    Flashcard("のどが かわきました", "I'm thirsty."),
                    Flashcard("そうですね", "I agree with you."),
                    Flashcard("そうしましょう", "Let's do that.")
                )
                14 -> listOf(
                    Flashcard("つけます", "turn on"),
                    Flashcard("けします", "turn off"),
                    Flashcard("あけます", "open"),
                    Flashcard("しめます", "close, shut"),
                    Flashcard("いそぎます", "hurry"),
                    Flashcard("まちます", "wait"),
                    Flashcard("とめます", "stop, park"),
                    Flashcard("まがります [みぎへ～]", "turn [to the right]"),
                    Flashcard("もちます", "hold"),
                    Flashcard("とります", "take, pass"),
                    Flashcard("てつだいます", "help (with a task)"),
                    Flashcard("よびます", "call"),
                    Flashcard("はなします", "speak, talk"),
                    Flashcard("みせます", "show"),
                    Flashcard("おしえます [じゅうしょを～]", "tell [an address]"),
                    Flashcard("はじめます", "start, begin"),
                    Flashcard("ふります [あめが～]", "rain"),
                    Flashcard("コピーします", "copy"),
                    Flashcard("エアコン", "air conditioner"),
                    Flashcard("パスポート", "passport"),
                    Flashcard("なまえ", "name"),
                    Flashcard("じゅうしょ", "address"),
                    Flashcard("ちず", "map"),
                    Flashcard("しお", "salt"),
                    Flashcard("さとう", "sugar"),
                    Flashcard("よみかた", "how to read, way of reading"),
                    Flashcard("～かた", "how to ~, way of ~ing"),
                    Flashcard("ゆっくり", "slowly, leisurely"),
                    Flashcard("すぐ", "immediately"),
                    Flashcard("また", "again"),
                    Flashcard("あとで", "later"),
                    Flashcard("もうすこし", "a little more"),
                    Flashcard("もう～", "~ more, another ~"),
                    Flashcard("さあ", "right (used when encouraging some action)"),
                    Flashcard("あれ？", "Oh! / Eh? (in surprise or wonder)"),
                    Flashcard("しんごうを みぎへ まがってください", "Turn right at the signal."),
                    Flashcard("まっすぐ", "straight"),
                    Flashcard("おつり", "change (from a purchase)")
                )
                15 -> listOf(
                    Flashcard("たちます", "stand up"),
                    Flashcard("すわります", "sit down"),
                    Flashcard("つかいます", "use"),
                    Flashcard("おきます", "put"),
                    Flashcard("つくります", "make, produce"),
                    Flashcard("うります", "sell"),
                    Flashcard("しります", "get to know"),
                    Flashcard("すみます", "be going to live"),
                    Flashcard("けんきゅうします", "do research"),
                    Flashcard("しっています", "know"),
                    Flashcard("すんでいます [おおさかに～]", "live [in Osaka]"),
                    Flashcard("しりょう", "materials, data"),
                    Flashcard("カタログ", "catalog"),
                    Flashcard("じこくひょう", "timetable"),
                    Flashcard("ふく", "clothes"),
                    Flashcard("せいひん", "products"),
                    Flashcard("ソフト", "software"),
                    Flashcard("せんもん", "specialty, field of study"),
                    Flashcard("はいしゃ", "dentist, dentist's"),
                    Flashcard("とこや", "barber, barber's"),
                    Flashcard("プレイガイド", "(theater) ticket agency"),
                    Flashcard("どくしん", "single, unmarried"),
                    Flashcard("とくに", "especially"),
                    Flashcard("おもいだします", "remember, recollect"),
                    Flashcard("ごかぞく", "your family"),
                    Flashcard("いらっしゃいます", "be (honorific equivalent of います)"),
                    Flashcard("こうこう", "senior high school")
                )
                16 -> listOf(
                    Flashcard("のります [でんしゃに～]", "ride, get on [a train]"),
                    Flashcard("おります [でんしゃを～]", "get off [a train]"),
                    Flashcard("のりかえます", "change (trains, etc.)"),
                    Flashcard("あびます [シャワーを～]", "take [a shower]"),
                    Flashcard("いれます", "put in, insert"),
                    Flashcard("だします", "take out, hand in, withdraw"),
                    Flashcard("はいります [だいがくに～]", "enter [a university]"),
                    Flashcard("でます [だいがくを～]", "graduate from [a university]"),
                    Flashcard("やめます [かいしゃを～]", "quit or retire from [a company]"),
                    Flashcard("おします", "press, push"),
                    Flashcard("わかい", "young"),
                    Flashcard("ながい", "long"),
                    Flashcard("みじかい", "short"),
                    Flashcard("あかるい", "bright, light"),
                    Flashcard("くらい", "dark"),
                    Flashcard("せが たかい", "tall (person)"),
                    Flashcard("あたまが いい", "clever, smart"),
                    Flashcard("からだ", "body"),
                    Flashcard("あたま", "head"),
                    Flashcard("かみ", "hair"),
                    Flashcard("かお", "face"),
                    Flashcard("め", "eye"),
                    Flashcard("みみ", "ear"),
                    Flashcard("くち", "mouth"),
                    Flashcard("は", "tooth"),
                    Flashcard("おなか", "stomach"),
                    Flashcard("あし", "leg, foot"),
                    Flashcard("サービス", "service"),
                    Flashcard("ジョギング", "jogging"),
                    Flashcard("シャワー", "shower"),
                    Flashcard("みどり", "green, greenery"),
                    Flashcard("おてら", "Buddhist temple"),
                    Flashcard("じんじゃ", "Shinto shrine"),
                    Flashcard("りゅうがくせい", "foreign student"),
                    Flashcard("～ばん", "number ~"),
                    Flashcard("どうやって", "in what way, how"),
                    Flashcard("どの～", "which ~ (of three or more)"),
                    Flashcard("まだまだです", "I still have a long way to go."),
                    Flashcard("おひきだしですか", "Are you making a withdrawal?"),
                    Flashcard("まず", "first of all"),
                    Flashcard("キャッシュカード", "cash card"),
                    Flashcard("あんしょうばんごう", "PIN, personal identification number"),
                    Flashcard("つぎに", "next, as a next step"),
                    Flashcard("きんがく", "amount of money"),
                    Flashcard("かくにん", "confirmation"),
                    Flashcard("ボタン", "button")
                )
                17 -> listOf(
                    Flashcard("おぼえます", "memorize"),
                    Flashcard("わすれます", "forget"),
                    Flashcard("なくします", "lose"),
                    Flashcard("はらいます", "pay"),
                    Flashcard("かえします", "give back, return"),
                    Flashcard("でかけます", "go out"),
                    Flashcard("ぬぎます", "take off (clothes, shoes, etc.)"),
                    Flashcard("もっていきます", "take (something)"),
                    Flashcard("もってきます", "bring (something)"),
                    Flashcard("しんぱいします", "worry"),
                    Flashcard("ざんぎょうします", "work overtime"),
                    Flashcard("しゅっちょうします", "go on a business trip"),
                    Flashcard("のみます [くすりを～]", "take [medicine]"),
                    Flashcard("はいります [おふろに～]", "take [a bath]"),
                    Flashcard("たいせつ[な]", "important, precious"),
                    Flashcard("だいじょうぶ[な]", "all right"),
                    Flashcard("あぶない", "dangerous"),
                    Flashcard("もんだい", "question, problem, trouble"),
                    Flashcard("こたえ", "answer"),
                    Flashcard("きんえん", "no smoking"),
                    Flashcard("けんこうほけんしょう", "health insurance card"),
                    Flashcard("かぜ", "cold"),
                    Flashcard("ねつ", "fever"),
                    Flashcard("びょうき", "illness, disease"),
                    Flashcard("くすり", "medicine"),
                    Flashcard("おふろ", "bath"),
                    Flashcard("うわぎ", "jacket, outerwear"),
                    Flashcard("したぎ", "underwear"),
                    Flashcard("～までに", "before ~, by ~ (time limit)"),
                    Flashcard("ですから", "therefore, so"),
                    Flashcard("どうしましたか", "What's the matter?"),
                    Flashcard("のど", "throat"),
                    Flashcard("～が いたいです", "I have a pain in my ~."),
                    Flashcard("おだいじに", "Take care of yourself.")
                )
                18 -> listOf(
                    Flashcard("できます", "be able to, can"),
                    Flashcard("あらいます", "wash"),
                    Flashcard("ひきます", "play (stringed instrument, piano)"),
                    Flashcard("うたいます", "sing"),
                    Flashcard("あつめます", "collect, gather"),
                    Flashcard("すてます", "throw away"),
                    Flashcard("かえます", "exchange, change"),
                    Flashcard("うんてんします", "drive"),
                    Flashcard("よやくします", "reserve, book"),
                    Flashcard("けんがくします", "visit some place for study"),
                    Flashcard("ピアノ", "piano"),
                    Flashcard("～メートル", "~ meter"),
                    Flashcard("こくさい～", "international ~"),
                    Flashcard("げんきん", "cash"),
                    Flashcard("しゅみ", "hobby"),
                    Flashcard("にっき", "diary"),
                    Flashcard("おいのり", "prayer"),
                    Flashcard("かちょう", "section chief"),
                    Flashcard("ぶちょう", "department chief"),
                    Flashcard("しゃちょう", "president of a company"),
                    Flashcard("どうぶつ", "animal"),
                    Flashcard("うま", "horse"),
                    Flashcard("へえ", "Really! (in surprise)"),
                    Flashcard("それはおもしろいですね", "That must be interesting."),
                    Flashcard("なかなか", "not easily (with negatives)"),
                    Flashcard("ぼくじょう", "ranch, stock farm"),
                    Flashcard("ほんとうですか", "Really?"),
                    Flashcard("ぜひ", "by all means")
                )
                19 -> listOf(
                    Flashcard("のぼります [やまに～]", "climb [a mountain]"),
                    Flashcard("とまります [ホテルに～]", "stay [at a hotel]"),
                    Flashcard("そうじします", "clean (a room)"),
                    Flashcard("せんたくします", "wash (clothes)"),
                    Flashcard("れんしゅうします", "practice"),
                    Flashcard("なります", "become"),
                    Flashcard("ねむい", "sleepy"),
                    Flashcard("つよい", "strong"),
                    Flashcard("よわい", "weak"),
                    Flashcard("ちょうしが いい", "be in good condition"),
                    Flashcard("ちょうしが わるい", "be in bad condition"),
                    Flashcard("ちょうし", "condition"),
                    Flashcard("ゴルフ", "golf"),
                    Flashcard("すもう", "sumo wrestling"),
                    Flashcard("パチンコ", "pachinko"),
                    Flashcard("おちゃ", "tea ceremony"),
                    Flashcard("ひ", "day, date"),
                    Flashcard("いちど", "once"),
                    Flashcard("いちども", "not once, never (with negatives)"),
                    Flashcard("だんだん", "gradually"),
                    Flashcard("もうすぐ", "soon"),
                    Flashcard("おかげさまで", "Thank you. (expressing gratitude)"),
                    Flashcard("かんぱい", "Bottoms up! / Cheers!"),
                    Flashcard("じつは", "actually, to tell the truth"),
                    Flashcard("ダイエット", "diet"),
                    Flashcard("なんかいも", "many times"),
                    Flashcard("しかし", "but, however"),
                    Flashcard("むり[な]", "excessive, impossible"),
                    Flashcard("からだに いい", "good for one's health"),
                    Flashcard("ケーキ", "cake")
                )
                20 -> listOf(
                    Flashcard("いります [ビザが～]", "need, require [a visa]"),
                    Flashcard("しらべます", "check, investigate"),
                    Flashcard("なおします", "repair, correct"),
                    Flashcard("しゅうりします", "repair"),
                    Flashcard("でんわします", "phone"),
                    Flashcard("ぼく", "I (informal, male)"),
                    Flashcard("きみ", "you (informal, to juniors)"),
                    Flashcard("～くん", "Mr. (informal, to juniors)"),
                    Flashcard("うん", "yes (informal)"),
                    Flashcard("ううん", "no (informal)"),
                    Flashcard("サラリーマン", "salaried worker, office worker"),
                    Flashcard("ことば", "word, language"),
                    Flashcard("ぶっか", "commodity prices"),
                    Flashcard("きもの", "kimono"),
                    Flashcard("ビザ", "visa"),
                    Flashcard("はじめ", "the beginning"),
                    Flashcard("おわり", "the end"),
                    Flashcard("こっち", "this way, this place (informal)"),
                    Flashcard("そっち", "that way, that place (informal)"),
                    Flashcard("あっち", "that way over there (informal)"),
                    Flashcard("どっち", "which one, which way (informal)"),
                    Flashcard("このあいだ", "the other day"),
                    Flashcard("みんなで", "all together"),
                    Flashcard("～けど", "but (informal)"),
                    Flashcard("くにへ かえるの？", "Are you going back to your country?"),
                    Flashcard("どう するの？", "What will you do?"),
                    Flashcard("どう しようかな", "What shall I do?"),
                    Flashcard("よかったら", "if you like"),
                    Flashcard("いろいろ", "various")
                )
                21 -> listOf(
                    Flashcard("おもいます", "think"),
                    Flashcard("いいます", "say"),
                    Flashcard("たります", "be enough, be sufficient"),
                    Flashcard("かちます", "win"),
                    Flashcard("まけます", "lose, be beaten"),
                    Flashcard("あります [おまつりが～]", "[a festival] be held, take place"),
                    Flashcard("やくにたちます", "be useful"),
                    Flashcard("むだ[な]", "wasteful"),
                    Flashcard("ふべん[な]", "inconvenient"),
                    Flashcard("おなじ", "the same"),
                    Flashcard("すごい", "awful, great"),
                    Flashcard("しゅしょう", "prime minister"),
                    Flashcard("だいとうりょう", "president"),
                    Flashcard("せいじ", "politics"),
                    Flashcard("ニュース", "news"),
                    Flashcard("スピーチ", "speech"),
                    Flashcard("しあい", "game, match"),
                    Flashcard("アルバイト", "side job"),
                    Flashcard("いけん", "opinion"),
                    Flashcard("おはなし", "talk, speech, story"),
                    Flashcard("ユーモア", "humor"),
                    Flashcard("デザイン", "design"),
                    Flashcard("こうつう", "transportation, traffic"),
                    Flashcard("ラッシュ", "rush hour"),
                    Flashcard("さいきん", "recently, these days"),
                    Flashcard("たぶん", "probably, perhaps, maybe"),
                    Flashcard("きっと", "surely"),
                    Flashcard("ほんとうに", "really"),
                    Flashcard("そんなに", "not so much (with negatives)"),
                    Flashcard("～について", "about ~, concerning ~"),
                    Flashcard("しかたがありません", "It can't be helped."),
                    Flashcard("しばらくですね", "It's been a long time."),
                    Flashcard("～でも のみませんか", "How about drinking ~ or something?"),
                    Flashcard("みないと…", "I've got to watch it."),
                    Flashcard("もちろん", "of course")
                )
                22 -> listOf(
                    Flashcard("きます [シャツを～]", "put on [a shirt, etc.]"),
                    Flashcard("はきます [くつを～]", "put on [shoes, trousers, etc.]"),
                    Flashcard("かぶります [ぼうしを～]", "put on [a hat, etc.]"),
                    Flashcard("かけます [めがねを～]", "put on [glasses]"),
                    Flashcard("うまれます", "be born"),
                    Flashcard("コート", "coat"),
                    Flashcard("スーツ", "suit"),
                    Flashcard("セーター", "sweater"),
                    Flashcard("ぼうし", "hat, cap"),
                    Flashcard("めがね", "glasses"),
                    Flashcard("よく", "often"),
                    Flashcard("おめでとうございます", "Congratulations."),
                    Flashcard("こちら", "this (polite)"),
                    Flashcard("やちん", "house rent"),
                    Flashcard("うーん", "Let me see."),
                    Flashcard("ダイニングキッチン", "kitchen with a dining area"),
                    Flashcard("わしつ", "Japanese-style room"),
                    Flashcard("おしいれ", "Japanese-style closet"),
                    Flashcard("ふとん", "Japanese-style mattress and quilt"),
                    Flashcard("アパート", "apartment")
                )
                23 -> listOf(
                    Flashcard("ききます [せんせいに～]", "ask [the teacher]"),
                    Flashcard("まわします", "turn"),
                    Flashcard("ひきます", "pull"),
                    Flashcard("かえます", "change"),
                    Flashcard("さわります [ドアに～]", "touch [a door]"),
                    Flashcard("でます [おつりが～]", "[change] come out"),
                    Flashcard("うごきます [とけいが～]", "[a watch] move, work"),
                    Flashcard("あるきます [みちを～]", "walk [along a road]"),
                    Flashcard("わたります [はしを～]", "cross [a bridge]"),
                    Flashcard("きをつけます [くるまに～]", "pay attention to [cars]"),
                    Flashcard("ひっこしします", "move (house)"),
                    Flashcard("でんきや", "electrician, electrical appliance store"),
                    Flashcard("～や", "person of ~ shop"),
                    Flashcard("サイズ", "size"),
                    Flashcard("おと", "sound"),
                    Flashcard("きかい", "machine"),
                    Flashcard("つまみ", "knob"),
                    Flashcard("こしょう", "breakdown"),
                    Flashcard("みち", "road, way"),
                    Flashcard("こうさてん", "crossroads, intersection"),
                    Flashcard("しんごう", "traffic light"),
                    Flashcard("かど", "corner"),
                    Flashcard("はし", "bridge"),
                    Flashcard("ちゅうしゃじょう", "parking lot, car park"),
                    Flashcard("～め", "the -th (indicating order)"),
                    Flashcard("おしょうがつ", "New Year's Day"),
                    Flashcard("ごちそうさまでした", "That was delicious."),
                    Flashcard("たてもの", "building"),
                    Flashcard("がいこくじんとうろくしょう", "alien registration card")
                )
                24 -> listOf(
                    Flashcard("くれます", "give (me)"),
                    Flashcard("つれていきます", "take (someone)"),
                    Flashcard("つれてきます", "bring (someone)"),
                    Flashcard("おくります [ひとを～]", "escort [someone], go with"),
                    Flashcard("しょうかいします", "introduce"),
                    Flashcard("あんないします", "show around, show the way"),
                    Flashcard("せつめいします", "explain"),
                    Flashcard("いれます [コーヒーを～]", "make [coffee]"),
                    Flashcard("おじいさん / おじいちゃん", "grandfather, old man"),
                    Flashcard("おばあさん / おばあちゃん", "grandmother, old woman"),
                    Flashcard("じゅんび", "preparation"),
                    Flashcard("いみ", "meaning"),
                    Flashcard("おかし", "sweets, snacks"),
                    Flashcard("ぜんぶ", "all"),
                    Flashcard("じぶんで", "by oneself"),
                    Flashcard("ほかに", "besides"),
                    Flashcard("ワゴンしゃ", "station wagon"),
                    Flashcard("おべんとう", "box lunch")
                )
                25 -> listOf(
                    Flashcard("かんがえます", "think, consider"),
                    Flashcard("つきます [えきに～]", "arrive [at the station]"),
                    Flashcard("りゅうがくします", "study abroad"),
                    Flashcard("とります [としを～]", "grow old"),
                    Flashcard("いなか", "countryside, hometown"),
                    Flashcard("たいしかん", "embassy"),
                    Flashcard("グループ", "group"),
                    Flashcard("チャンス", "chance"),
                    Flashcard("おく", "hundred million"),
                    Flashcard("もし [～たら]", "if ~"),
                    Flashcard("いくら [～でも]", "however ~, even if ~"),
                    Flashcard("てんきん", "transfer"),
                    Flashcard("こと", "thing, matter"),
                    Flashcard("いっぱい のみましょう", "Let's have a drink together."),
                    Flashcard("いろいろ おせわに なりました", "Thank you for everything."),
                    Flashcard("がんばります", "I'll do my best."),
                    Flashcard("どうぞ おげんきで", "Best of luck. (said when expecting a long separation)")
                )
                // This is the line that fixes the error
                else -> emptyList()
            }
        )
    }
}

// Helper function to get a specific lesson's flashcards
fun getFlashcardSet(id: String): FlashcardSet? {
    return getAllFlashcardSets().find { it.id == id }
}