package com.example.yourappname

// We reuse the Flashcard and FlashcardSet data classes from the N5 data file.

fun getAllN4FlashcardSets(): List<FlashcardSet> {
    return (26..50).map { lessonNumber ->
        FlashcardSet(
            id = "minna_L$lessonNumber",
            title = "Lesson $lessonNumber",
            cards = when (lessonNumber) {
                26 -> listOf(
                    Flashcard("みます", "check, take a look at"),
                    Flashcard("さがします", "look for, search"),
                    Flashcard("おくれます", "be late (for an appointment etc)"),
                    Flashcard("まにあいます", "be in time (for an appointment etc)"),
                    Flashcard("やります", "do"),
                    Flashcard("ひろいます", "pick up"),
                    Flashcard("れんらくします", "contact, get in touch with"),
                    Flashcard("きぶんがいい", "feel well"),
                    Flashcard("きぶんがわるい", "feel ill"),
                    Flashcard("うんどうかい", "athletic meeting, sports day"),
                    Flashcard("ぼんおどり", "Bon Festival dance"),
                    Flashcard("フリーマーケット", "flea market"),
                    Flashcard("ばしょ", "place"),
                    Flashcard("ボランティア", "volunteer"),
                    Flashcard("さいふ", "wallet, purse"),
                    Flashcard("ごみ", "garbage, rubbish, dust"),
                    Flashcard("こっかいぎじどう", "the Diet building"),
                    Flashcard("へいじつ", "weekday"),
                    Flashcard("～べん", "~ dialect"),
                    Flashcard("こんど", "next time, another time"),
                    Flashcard("ずいぶん", "very, pretty"),
                    Flashcard("ちょくせつ", "directly"),
                    Flashcard("いつでも", "any time"),
                    Flashcard("どこでも", "anywhere"),
                    Flashcard("だれでも", "anybody"),
                    Flashcard("なんでも", "anything"),
                    Flashcard("こんな～", "~ like this"),
                    Flashcard("そんな～", "~ like that (near you)"),
                    Flashcard("あんな～", "~ like that (far from you)"),
                    Flashcard("かたづきます", "(boxes) be put in order, tidy up"),
                    Flashcard("だします", "put out (the rubbish)"),
                    Flashcard("もえるごみ", "burnable rubbish"),
                    Flashcard("おきば", "place where something is put"),
                    Flashcard("よこ", "side"),
                    Flashcard("びん", "bottle"),
                    Flashcard("かん", "can"),
                    Flashcard("ガス", "gas"),
                    Flashcard("うちゅう", "space, universe"),
                    Flashcard("～さま", "Mr, Mrs (respectful)"),
                    Flashcard("うちゅうせん", "Spaceship"),
                    Flashcard("こわい", "be afraid of"),
                    Flashcard("うちゅうステーション", "space station"),
                    Flashcard("ちがいます", "be different"),
                    Flashcard("うちゅうひこうし", "astronaut")
                )
                27 -> listOf(
                    Flashcard("かいます", "keep (a pet), raise (an animal)"),
                    Flashcard("はしります", "run, drive (along a road)"),
                    Flashcard("みえます", "(a mountain) can be seen"),
                    Flashcard("きこえます", "(a sound) can be heard"),
                    Flashcard("できます", "(a road) be made, be completed"),
                    Flashcard("ひらきます", "set up (a class), open, hold"),
                    Flashcard("しんぱい(な)", "worried, anxious"),
                    Flashcard("ペット", "pet"),
                    Flashcard("とり", "bird"),
                    Flashcard("こえ", "voice"),
                    Flashcard("なみ", "wave"),
                    Flashcard("はなび", "fireworks"),
                    Flashcard("どうぐ", "tool, instrument, equipment"),
                    Flashcard("クリーニング", "(dry) cleaning, laundry"),
                    Flashcard("いえ", "house, home"),
                    Flashcard("マンション", "condominium, apartment"),
                    Flashcard("キッチン", "kitchen"),
                    Flashcard("～きょうしつ", "~ class"),
                    Flashcard("パーティールーム", "party room"),
                    Flashcard("かた", "person (respectful)"),
                    Flashcard("～ご", "after ~ (duration)"),
                    Flashcard("～しか", "only ~ (used with negatives)"),
                    Flashcard("ほかの", "other"),
                    Flashcard("はっきり", "clearly"),
                    Flashcard("かぐ", "furniture"),
                    Flashcard("ほんだな", "bookcase"),
                    Flashcard("いつか", "one day, some day"),
                    Flashcard("たてます", "build"),
                    Flashcard("すばらしい", "wonderful"),
                    Flashcard("こどもたち", "children"),
                    Flashcard("だいすき(な)", "like very much"),
                    Flashcard("しゅじんこう", "hero, heroine"),
                    Flashcard("かたち", "shape"),
                    Flashcard("ふしぎ(な)", "fantastic, mysterious"),
                    Flashcard("ポケット", "pocket"),
                    Flashcard("たとえば", "for example"),
                    Flashcard("つけます", "attach, put on"),
                    Flashcard("じゆうに", "freely"),
                    Flashcard("そら", "sky"),
                    Flashcard("とびます", "fly"),
                    Flashcard("むかし", "old days, ancient times"),
                    Flashcard("じぶん", "oneself"),
                    Flashcard("しょうらい", "future")
                )
                28 -> listOf(
                    Flashcard("うれます", "[bread] sell, be sold"),
                    Flashcard("おどります", "dance"),
                    Flashcard("かみます", "chew, bite"),
                    Flashcard("えらびます", "choose"),
                    Flashcard("ちがいます", "be different"),
                    Flashcard("かよいます", "go to and from, commute"),
                    Flashcard("メモします", "take a memo"),
                    Flashcard("まじめ[な]", "serious"),
                    Flashcard("ねっしん[な]", "earnest"),
                    Flashcard("やさしい", "gentle, kind"),
                    Flashcard("えらい", "great, admirable"),
                    Flashcard("ちょうどいい", "proper, just right"),
                    Flashcard("しゅうかん", "custom"),
                    Flashcard("けいけん", "experience"),
                    Flashcard("ちから", "power"),
                    Flashcard("にんき", "popularity"),
                    Flashcard("かたち", "shape"),
                    Flashcard("いろ", "color"),
                    Flashcard("あじ", "taste"),
                    Flashcard("ガム", "chewing gum"),
                    Flashcard("しなもの", "goods"),
                    Flashcard("ねだん", "price"),
                    Flashcard("きゅうりょう", "salary"),
                    Flashcard("ボーナス", "bonus"),
                    Flashcard("ばんぐみ", "program"),
                    Flashcard("ドラマ", "drama"),
                    Flashcard("しょうせつ", "novel"),
                    Flashcard("しょうせつか", "novelist"),
                    Flashcard("かしゅ", "singer"),
                    Flashcard("かんりにん", "janitor"),
                    Flashcard("むすこ", "(my) son"),
                    Flashcard("むすこさん", "(someone else's) son"),
                    Flashcard("むすめ", "(my) daughter"),
                    Flashcard("むすめさん", "(someone else's) daughter"),
                    Flashcard("じぶん", "oneself"),
                    Flashcard("しょうらい", "future"),
                    Flashcard("しばらく", "a little while"),
                    Flashcard("たいてい", "usually, mostly"),
                    Flashcard("それに", "in addition"),
                    Flashcard("それで", "and so"),
                    Flashcard("おねがいがあるんですが", "I have a favor to ask"),
                    Flashcard("ホームステイ", "homestay"),
                    Flashcard("かいわ", "conversation"),
                    Flashcard("おしゃべりします", "chat"),
                    Flashcard("おしらせ", "notice"),
                    Flashcard("ひにち", "date"),
                    Flashcard("どようび", "Saturday"),
                    Flashcard("たいいくかん", "gymnasium"),
                    Flashcard("むりょう", "free of charge")
                )
                29 -> listOf(
                    Flashcard("あきます", "(a door) open"),
                    Flashcard("しまります", "(a door) close, shut"),
                    Flashcard("つきます", "(a light) come on, be turned on"),
                    Flashcard("きえます", "(a light) go off"),
                    Flashcard("こわれます", "(a chair) break"),
                    Flashcard("われます", "(a glass) break, smash"),
                    Flashcard("おれます", "(a tree) break, snap"),
                    Flashcard("やぶれます", "(paper) tear"),
                    Flashcard("よごれます", "(clothes) get dirty"),
                    Flashcard("つきます", "(a pocket) be attached"),
                    Flashcard("はずれます", "(a button) be undone"),
                    Flashcard("とまります", "(a car) stop, park"),
                    Flashcard("まちがえます", "make a mistake"),
                    Flashcard("おとします", "drop, lose"),
                    Flashcard("かかります", "be locked"),
                    Flashcard("ふきます", "wipe"),
                    Flashcard("とりかえます", "change"),
                    Flashcard("かたづけます", "put in order, tidy up"),
                    Flashcard("おさら", "plate, dish"),
                    Flashcard("おちゃわん", "(rice) bowl"),
                    Flashcard("コップ", "glass (vessel)"),
                    Flashcard("ガラス", "glass (material)"),
                    Flashcard("ふくろ", "bag"),
                    Flashcard("しょるい", "document, papers"),
                    Flashcard("えだ", "branch, twig"),
                    Flashcard("えきいん", "station attendant"),
                    Flashcard("こうばん", "police box"),
                    Flashcard("スピーチ", "speech"),
                    Flashcard("へんじ", "reply, answer"),
                    Flashcard("おさきにどうぞ", "After you / Go ahead, please"),
                    Flashcard("わすれもの", "things left behind, lost property"),
                    Flashcard("このくらい", "about this (big)"),
                    Flashcard("～がわ", "~ side"),
                    Flashcard("～へん", "around ~, ~ about"),
                    Flashcard("おぼえていません", "I don't remember"),
                    Flashcard("あみだな", "overhead rack"),
                    Flashcard("たしか", "I'm pretty sure"),
                    Flashcard("ああ、よかった", "Oh, that's great! / Thank goodness!"),
                    Flashcard("じしん", "earthquake"),
                    Flashcard("かべ", "wall"),
                    Flashcard("はり", "hands (of a clock)"),
                    Flashcard("さします", "point"),
                    Flashcard("えきまえ", "the area in front of a station"),
                    Flashcard("たおれます", "fall down"),
                    Flashcard("にし", "west"),
                    Flashcard("～のほう", "direction of ~"),
                    Flashcard("もえます", "burn"),
                    Flashcard("レポーター", "reporter")
                )
                30 -> listOf(
                    Flashcard("はります", "put up, post, paste"),
                    Flashcard("かけます", "hang"),
                    Flashcard("かざります", "display, decorate"),
                    Flashcard("ならべます", "arrange, line up"),
                    Flashcard("うえます", "plant"),
                    Flashcard("もどします", "return, put back"),
                    Flashcard("まとめます", "put together, sum up"),
                    Flashcard("しまいます", "put things away"),
                    Flashcard("きめます", "decide"),
                    Flashcard("よしゅうします", "prepare one's lesson"),
                    Flashcard("ふくしゅうします", "review one's lesson"),
                    Flashcard("そのままにします", "leave things as they are"),
                    Flashcard("じゅぎょう", "class"),
                    Flashcard("こうぎ", "lecture"),
                    Flashcard("ミーティング", "meeting"),
                    Flashcard("よてい", "plan, schedule"),
                    Flashcard("おしらせ", "notice"),
                    Flashcard("ガイドブック", "guidebook"),
                    Flashcard("カレンダー", "calendar"),
                    Flashcard("ポスター", "poster"),
                    Flashcard("よていひょう", "schedule"),
                    Flashcard("ごみばこ", "trash can, bin"),
                    Flashcard("にんぎょう", "doll"),
                    Flashcard("かびん", "vase"),
                    Flashcard("かがみ", "mirror"),
                    Flashcard("ひきだし", "drawer"),
                    Flashcard("げんかん", "front door, porch, entrance hall"),
                    Flashcard("ろうか", "hallway, corridor"),
                    Flashcard("かべ", "wall"),
                    Flashcard("いけ", "pond"),
                    Flashcard("もとのところ", "original place"),
                    Flashcard("まわり", "round, around"),
                    Flashcard("まんなか", "center"),
                    Flashcard("すみ", "corner"),
                    Flashcard("まだ", "still"),
                    Flashcard("リュック", "rucksack"),
                    Flashcard("ひじょうぶくろ", "emergency kit"),
                    Flashcard("ひじょうじ", "emergency"),
                    Flashcard("せいかつします", "live"),
                    Flashcard("かいちゅうでんとう", "torch, flashlight"),
                    Flashcard("～とか、～とか", "~, ~ and so on"),
                    Flashcard("まるい", "round"),
                    Flashcard("ある～", "one ~, a certain ~"),
                    Flashcard("ゆめをみます", "dream"),
                    Flashcard("うれしい", "glad, happy"),
                    Flashcard("いや[な]", "hateful, disagreeable"),
                    Flashcard("すると", "and, then"),
                    Flashcard("めがさめます", "wake up")
                )
                31 -> listOf(
                    Flashcard("はじまります", "[a ceremony] begin, start"),
                    Flashcard("つづけます", "continue"),
                    Flashcard("みつけます", "find"),
                    Flashcard("うけます", "take [an examination]"),
                    Flashcard("にゅうがくします", "enter [a university]"),
                    Flashcard("そつぎょうします", "graduate [from a university]"),
                    Flashcard("しゅっせきします", "attend [a meeting]"),
                    Flashcard("きゅうけいします", "take a break, take a rest"),
                    Flashcard("れんきゅう", "consecutive holidays"),
                    Flashcard("さくぶん", "essay, composition"),
                    Flashcard("てんらんかい", "exhibition"),
                    Flashcard("けっこんしき", "wedding ceremony"),
                    Flashcard("おそうしき", "funeral"),
                    Flashcard("しき", "ceremony"),
                    Flashcard("ほんしゃ", "head office"),
                    Flashcard("してん", "branch office"),
                    Flashcard("きょうかい", "church"),
                    Flashcard("だいがくいん", "graduate school"),
                    Flashcard("どうぶつえん", "zoo"),
                    Flashcard("おんせん", "hot spring, spa"),
                    Flashcard("おきゃくさん", "visitor, guest, customer, client"),
                    Flashcard("だれか", "somebody"),
                    Flashcard("～のほう", "place toward ~, direction of ~"),
                    Flashcard("ずっと", "all the time"),
                    Flashcard("のこります", "remain, be left"),
                    Flashcard("つきに", "per month"),
                    Flashcard("ふつうの", "ordinary, common, usual"),
                    Flashcard("インターネット", "Internet"),
                    Flashcard("むら", "village"),
                    Flashcard("えいがかん", "cinema"),
                    Flashcard("いや[な]", "disagreeable, hateful"),
                    Flashcard("そら", "sky"),
                    Flashcard("とじます", "close"),
                    Flashcard("とかい", "city"),
                    Flashcard("こどもたち", "children"),
                    Flashcard("せかいじゅう", "all over the world"),
                    Flashcard("じゆうに", "freely"),
                    Flashcard("あつまります", "gather"),
                    Flashcard("うつくしい", "beautiful"),
                    Flashcard("しぜん", "nature"),
                    Flashcard("すばらしさ", "goodness, virtue"),
                    Flashcard("きがつきます", "notice, become aware of")
                )
                32 -> listOf(
                    Flashcard("うんどうします", "(take) exercise"),
                    Flashcard("せいこうします", "succeed"),
                    Flashcard("しっぱいします", "fail [an examination]"),
                    Flashcard("ごうかくします", "pass [an examination]"),
                    Flashcard("やみます", "[rain] stop"),
                    Flashcard("はれます", "clear up"),
                    Flashcard("くもります", "get cloudy"),
                    Flashcard("つづきます", "[fever] continue"),
                    Flashcard("ひきます", "catch [a cold]"),
                    Flashcard("ひやします", "cool"),
                    Flashcard("こみます", "[a road] get crowded"),
                    Flashcard("すきます", "[a road] get less crowded"),
                    Flashcard("でます", "participate [in a match], attend [a party]"),
                    Flashcard("むりをします", "overdo things"),
                    Flashcard("じゅうぶん[な]", "enough, sufficient"),
                    Flashcard("おかしい", "strange, funny"),
                    Flashcard("うるさい", "noisy"),
                    Flashcard("せんせい", "doctor"),
                    Flashcard("やけど", "burning"),
                    Flashcard("けが", "injury"),
                    Flashcard("せき", "cough"),
                    Flashcard("インフルエンザ", "influenza"),
                    Flashcard("そら", "sky"),
                    Flashcard("たいよう", "sun"),
                    Flashcard("ほし", "star"),
                    Flashcard("かぜ", "wind"),
                    Flashcard("ひがし", "east"),
                    Flashcard("にし", "west"),
                    Flashcard("みなみ", "south"),
                    Flashcard("きた", "north"),
                    Flashcard("こくさい～", "international ~"),
                    Flashcard("すいどう", "faucet, tap, water supply"),
                    Flashcard("エンジン", "engine"),
                    Flashcard("チーム", "team"),
                    Flashcard("こんや", "this evening"),
                    Flashcard("ゆうがた", "late afternoon"),
                    Flashcard("まえ", "a time in the past, before"),
                    Flashcard("おそく", "late (time)"),
                    Flashcard("こんなに", "this (much, etc.)"),
                    Flashcard("そんなに", "that (much, etc.)"),
                    Flashcard("あんなに", "that (much, etc.)"),
                    Flashcard("ヨーロッパ", "Europe"),
                    Flashcard("げんき", "vigor"),
                    Flashcard("い", "stomach"),
                    Flashcard("ストレス", "stress"),
                    Flashcard("それは いけませんね", "I'm sorry to hear that."),
                    Flashcard("ほしうらない", "horoscope"),
                    Flashcard("おうしざ", "Taurus"),
                    Flashcard("はたらきすぎ", "overworking"),
                    Flashcard("こまります", "be in trouble, have a problem"),
                    Flashcard("たからくじ", "lottery"),
                    Flashcard("あたります", "win [a lottery]"),
                    Flashcard("けんこう", "health"),
                    Flashcard("れんあい", "romantic love"),
                    Flashcard("こいびと", "sweetheart, boyfriend, girlfriend"),
                    Flashcard("ラッキーアイテム", "something lucky"),
                    Flashcard("いし", "stone")
                )
                33 -> listOf(
                    Flashcard("にげます", "run away"),
                    Flashcard("さわぎます", "make a noise"),
                    Flashcard("あきらめます", "give up"),
                    Flashcard("なげます", "throw"),
                    Flashcard("まもります", "keep, follow, obey"),
                    Flashcard("はじまります", "[a ceremony] begin, start"),
                    Flashcard("しゅっせきします", "attend [a meeting]"),
                    Flashcard("つたえます", "convey"),
                    Flashcard("ちゅういします", "be careful [of cars]"),
                    Flashcard("はずします", "be away [from one's desk]"),
                    Flashcard("もどります", "come back, return"),
                    Flashcard("あります", "have [a telephone call]"),
                    Flashcard("リサイクルします", "recycle"),
                    Flashcard("だめ[な]", "no good, not permitted, impossible"),
                    Flashcard("おなじ", "same"),
                    Flashcard("けいさつ", "police (station)"),
                    Flashcard("せき", "seat"),
                    Flashcard("マーク", "mark, symbol"),
                    Flashcard("ボール", "ball"),
                    Flashcard("しめきり", "deadline"),
                    Flashcard("きそく", "regulation, rule"),
                    Flashcard("きけん", "danger"),
                    Flashcard("しようきんし", "Do not use"),
                    Flashcard("たちいりきんし", "Do not enter"),
                    Flashcard("じょこう", "Go slow"),
                    Flashcard("いりぐち", "entrance"),
                    Flashcard("でぐち", "exit"),
                    Flashcard("ひじょうぐち", "emergency exit"),
                    Flashcard("むりょう", "Free of Charge"),
                    Flashcard("わりびき", "Discount"),
                    Flashcard("のみほうだい", "All You Can Drink"),
                    Flashcard("しようちゅう", "In use"),
                    Flashcard("ぼしゅうちゅう", "Applications wanted"),
                    Flashcard("～ちゅう", "-ing"),
                    Flashcard("どういう～", "what (kind of ~)"),
                    Flashcard("いくら[～でも]", "however ~, even if ~"),
                    Flashcard("もう", "(not) any longer (with negatives)"),
                    Flashcard("あと～", "~ left"),
                    Flashcard("～ほど", "about ~"),
                    Flashcard("ちゅうしゃいはん", "parking violation"),
                    Flashcard("ばっきん", "fine"),
                    Flashcard("じしん", "earthquake"),
                    Flashcard("おきます", "happen"),
                    Flashcard("たすけあいます", "help each other"),
                    Flashcard("もともと", "originally"),
                    Flashcard("かなしい", "sad"),
                    Flashcard("もっと", "more"),
                    Flashcard("あいさつ", "greeting, address"),
                    Flashcard("あいて", "the other person"),
                    Flashcard("きもち", "feeling")
                )
                34 -> listOf(
                    Flashcard("みがきます", "brush, polish"),
                    Flashcard("くみたてます", "assemble"),
                    Flashcard("おります", "bend, fold, break, snap"),
                    Flashcard("きがつきます", "notice, become aware of"),
                    Flashcard("つけます", "put in, attach"),
                    Flashcard("みつかります", "be found"),
                    Flashcard("しつもんします", "ask a question"),
                    Flashcard("ほそい", "thin (of small diameter)"),
                    Flashcard("ふとい", "thick (of large diameter)"),
                    Flashcard("ぼんおどり", "Bon Festival dance"),
                    Flashcard("スポーツクラブ", "sports club"),
                    Flashcard("かぐ", "furniture"),
                    Flashcard("キー", "key"),
                    Flashcard("シートベルト", "seat belt"),
                    Flashcard("せつめいしょ", "explanatory pamphlet, instruction book"),
                    Flashcard("ず", "figure, drawing"),
                    Flashcard("せん", "line"),
                    Flashcard("やじるし", "arrow (sign)"),
                    Flashcard("くろ", "black (noun)"),
                    Flashcard("しろ", "white (noun)"),
                    Flashcard("あか", "red (noun)"),
                    Flashcard("あお", "blue (noun)"),
                    Flashcard("こん", "navy blue, dark blue (noun)"),
                    Flashcard("きいろ", "yellow (noun)"),
                    Flashcard("ちゃいろ", "brown (noun)"),
                    Flashcard("しょうゆ", "soy sauce"),
                    Flashcard("ソース", "sauce, Worcestershire sauce"),
                    Flashcard("～か～", "~ or ~"),
                    Flashcard("ゆうべ", "last night"),
                    Flashcard("さっき", "a short while ago"),
                    Flashcard("さどう", "tea ceremony"),
                    Flashcard("おちゃをたてます", "make green tea"),
                    Flashcard("さきに", "first (when doing something before something else)"),
                    Flashcard("のせます", "place on, load on"),
                    Flashcard("これでいいですか", "Is this all right?"),
                    Flashcard("にがい", "bitter"),
                    Flashcard("おやこどんぶり", "a bowl of cooked rice with chicken and egg"),
                    Flashcard("ざいりょう", "material, ingredient"),
                    Flashcard("～ぶん", "~ portion (for indicating quantity)"),
                    Flashcard("～グラム", "~ gram"),
                    Flashcard("～こ", "(counter for small objects)"),
                    Flashcard("たまねぎ", "onion"),
                    Flashcard("よんぶんのいち", "one fourth"),
                    Flashcard("ちょうみりょう", "seasoning, flavoring"),
                    Flashcard("なべ", "pan, pot"),
                    Flashcard("ひ", "fire, heating"),
                    Flashcard("ひにかけます", "put on the stove"),
                    Flashcard("にます", "cook, boil"),
                    Flashcard("にえます", "be cooked, be boiled"),
                    Flashcard("どんぶり", "ceramic bowl")
                )
                35 -> listOf(
                    Flashcard("さきます", "bloom"),
                    Flashcard("かわります", "change (e.g. the color)"),
                    Flashcard("こまります", "be in trouble, have a problem"),
                    Flashcard("つけます", "draw, mark (e.g. a circle)"),
                    Flashcard("ひろいます", "pick up"),
                    Flashcard("かかります", "get through (on the telephone)"),
                    Flashcard("らく[な]", "comfortable, easy"),
                    Flashcard("ただしい", "correct, right"),
                    Flashcard("めずらしい", "rare, uncommon"),
                    Flashcard("かた", "person (respectful)"),
                    Flashcard("むこう", "over there, the other side"),
                    Flashcard("しま", "island"),
                    Flashcard("むら", "village"),
                    Flashcard("みなと", "port, harbor"),
                    Flashcard("きんじょ", "neighborhood, vicinity"),
                    Flashcard("おくじょう", "rooftop"),
                    Flashcard("かいがい", "overseas"),
                    Flashcard("やまのぼり", "mountain climbing"),
                    Flashcard("ハイキング", "hiking"),
                    Flashcard("きかい", "chance, opportunity"),
                    Flashcard("きょか", "permission"),
                    Flashcard("まる", "circle"),
                    Flashcard("そうさ", "operation"),
                    Flashcard("ほうほう", "method"),
                    Flashcard("せつび", "equipment, facilities"),
                    Flashcard("カーテン", "curtain"),
                    Flashcard("ひも", "string"),
                    Flashcard("ふた", "lid, cover, cap"),
                    Flashcard("は", "leaf"),
                    Flashcard("きょく", "a piece of music"),
                    Flashcard("たのしみ", "pleasure, enjoyment, expectation"),
                    Flashcard("もっと", "more"),
                    Flashcard("はじめに", "first"),
                    Flashcard("これでおわります", "We'll finish now."),
                    Flashcard("それなら", "in that case"),
                    Flashcard("やこうバス", "night bus"),
                    Flashcard("りょこうしゃ", "travel agency"),
                    Flashcard("くわしい", "detailed"),
                    Flashcard("スキーじょう", "ski resort, ski ground"),
                    Flashcard("しゅ", "red"),
                    Flashcard("まじわります", "keep company with"),
                    Flashcard("ことわざ", "proverb"),
                    Flashcard("なかよくします", "be on good terms with"),
                    Flashcard("ひつよう[な]", "necessary, essential")
                )
                36 -> listOf(
                    Flashcard("あいます", "encounter [an accident]"),
                    Flashcard("ちょきんします", "save money"),
                    Flashcard("すぎます", "pass [7 o'clock]"),
                    Flashcard("なれます", "get accustomed to [one's job]"),
                    Flashcard("くさります", "[food] rot"),
                    Flashcard("けんどう", "kendo"),
                    Flashcard("じゅうどう", "judo"),
                    Flashcard("ラッシュ", "rush hour"),
                    Flashcard("うちゅう", "space, universe"),
                    Flashcard("きょく", "a piece of music"),
                    Flashcard("まいしゅう", "every week"),
                    Flashcard("まいつき", "every month"),
                    Flashcard("まいとし / まいねん", "every year"),
                    Flashcard("このごろ", "these days"),
                    Flashcard("やっと", "finally"),
                    Flashcard("かなり", "fairly"),
                    Flashcard("かならず", "without fail, by any means"),
                    Flashcard("ぜったいに", "absolutely (not)"),
                    Flashcard("じょうずに", "well, skillfully"),
                    Flashcard("できるだけ", "as much as possible"),
                    Flashcard("ほとんど", "almost all, hardly, scarcely"),
                    Flashcard("おきゃくさま", "visitor, guest, customer (respectful)"),
                    Flashcard("とくべつ[な]", "special"),
                    Flashcard("していらっしゃいます", "be doing (respectful)"),
                    Flashcard("すいえい", "swimming"),
                    Flashcard("ちがいます", "be different"),
                    Flashcard("つかっていらっしゃるんですね", "You're using, aren't you? (respectful)"),
                    Flashcard("チャレンジします", "challenge"),
                    Flashcard("きもち", "spirit, mood"),
                    Flashcard("のりもの", "vehicle, means of transportation"),
                    Flashcard("～せいき", "-th century"),
                    Flashcard("とおく", "far, remote place"),
                    Flashcard("めずらしい", "rare, uncommon"),
                    Flashcard("きしゃ", "locomotive"),
                    Flashcard("きせん", "steam boat"),
                    Flashcard("おおぜいの～", "many (people)"),
                    Flashcard("はこびます", "carry, transport"),
                    Flashcard("りようします", "use"),
                    Flashcard("じゆうに", "freely")
                )
                37 -> listOf(
                    Flashcard("ほめます", "praise"),
                    Flashcard("しかります", "scold"),
                    Flashcard("さそいます", "invite, ask someone to join"),
                    Flashcard("おこします", "wake (someone) up"),
                    Flashcard("しょうたいします", "invite"),
                    Flashcard("たのみます", "ask, request"),
                    Flashcard("ちゅういします", "warn, advise"),
                    Flashcard("とります", "rob, steal"),
                    Flashcard("ふみます", "step on (someone's foot)"),
                    Flashcard("こわします", "break, destroy"),
                    Flashcard("よごします", "make dirty"),
                    Flashcard("おこないます", "hold, carry out, practice"),
                    Flashcard("ゆしゅつします", "export"),
                    Flashcard("ゆにゅうします", "import"),
                    Flashcard("ほんやくします", "translate"),
                    Flashcard("はつめいします", "invent"),
                    Flashcard("はっけんします", "discover"),
                    Flashcard("せっけいします", "design, plan"),
                    Flashcard("こめ", "rice"),
                    Flashcard("むぎ", "barley, wheat"),
                    Flashcard("せきゆ", "oil"),
                    Flashcard("げんりょう", "raw material"),
                    Flashcard("デート", "date"),
                    Flashcard("どろぼう", "thief, robber"),
                    Flashcard("けいかん", "policeman"),
                    Flashcard("けんちくか", "architect"),
                    Flashcard("かがくしゃ", "scientist"),
                    Flashcard("まんが", "cartoon, comic"),
                    Flashcard("せかいじゅう", "all over the world"),
                    Flashcard("～じゅう", "all over ~"),
                    Flashcard("～によって", "by ~"),
                    Flashcard("よかったですね", "That's lucky, isn't it?"),
                    Flashcard("うめたてます", "reclaim"),
                    Flashcard("ぎじゅつ", "technology, technique"),
                    Flashcard("とち", "land"),
                    Flashcard("そうおん", "noise"),
                    Flashcard("りようします", "use"),
                    Flashcard("アクセス", "access"),
                    Flashcard("ごうか[な]", "gorgeous"),
                    Flashcard("ちょうこく", "engraving, carving, sculpture"),
                    Flashcard("ねむります", "sleep"),
                    Flashcard("ほります", "engrave, carve"),
                    Flashcard("なかま", "colleague, friend"),
                    Flashcard("そのあと", "after that"),
                    Flashcard("いっしょうけんめい", "with all one's effort"),
                    Flashcard("ねずみ", "mouse"),
                    Flashcard("いっぴきもいません", "There is not a single (mouse)")
                )
                38 -> listOf(
                    Flashcard("さんかします", "join [a tour], participate, attend"),
                    Flashcard("そだてます", "breed, bring up"),
                    Flashcard("はこびます", "carry, transport"),
                    Flashcard("にゅういんします", "enter hospital"),
                    Flashcard("たいいんします", "leave hospital"),
                    Flashcard("いれます", "turn on [the power switch]"),
                    Flashcard("きります", "turn off [the power switch]"),
                    Flashcard("かけます", "lock"),
                    Flashcard("つきます", "tell [a lie]"),
                    Flashcard("きもちがいい", "pleasant, agreeable"),
                    Flashcard("きもちがわるい", "unpleasant, disgusting"),
                    Flashcard("おおきな～", "large~, big~"),
                    Flashcard("ちいさな～", "small~, little~"),
                    Flashcard("あかちゃん", "baby"),
                    Flashcard("しょうがっこう", "elementary school"),
                    Flashcard("ちゅうがっこう", "junior high school"),
                    Flashcard("えきまえ", "the area in front of the station"),
                    Flashcard("かいがん", "seaside, seashore"),
                    Flashcard("こうじょう", "factory"),
                    Flashcard("むら", "village"),
                    Flashcard("かな", "hiragana and katakana script"),
                    Flashcard("ゆびわ", "ring"),
                    Flashcard("でんげん", "power switch"),
                    Flashcard("しゅうかん", "habit"),
                    Flashcard("けんこう", "health"),
                    Flashcard("～せい", "made in ~"),
                    Flashcard("おととし", "the year before last"),
                    Flashcard("あ、いけない", "Oops! / Oh, no!"),
                    Flashcard("おさきにしつれいします", "Excuse me (for leaving before you)."),
                    Flashcard("かいらん", "circular"),
                    Flashcard("けんきゅうしつ", "study room, professor's office, laboratory"),
                    Flashcard("きちんと", "neatly, tidily"),
                    Flashcard("せいりします", "sort (things) out"),
                    Flashcard("～というほん", "the book entitled ~"),
                    Flashcard("～さつ", "(counter for books, etc.)"),
                    Flashcard("はんこ", "seal, stamp"),
                    Flashcard("おします", "affix [a seal], stamp"),
                    Flashcard("ふたご", "twins"),
                    Flashcard("しまい", "sisters"),
                    Flashcard("５ねんせい", "fifth grade, fifth year"),
                    Flashcard("にています", "resemble, be like"),
                    Flashcard("せいかく", "character"),
                    Flashcard("おとなしい", "quiet, gentle"),
                    Flashcard("やさしい", "kind, gentle, tender-hearted"),
                    Flashcard("せわをします", "take care of"),
                    Flashcard("じかんがたちます", "time passes by"),
                    Flashcard("だいすき[な]", "like very much"),
                    Flashcard("～てん", "- points"),
                    Flashcard("きがつよい", "tough, strong-willed"),
                    Flashcard("けんかします", "quarrel, fight"),
                    Flashcard("ふしぎ[な]", "mysterious, strange"),
                    Flashcard("ねんれい", "age"),
                    Flashcard("しかた", "way (of doing something)")
                )
                39 -> listOf(
                    Flashcard("こたえます", "answer a question"),
                    Flashcard("たおれます", "a building falls down"),
                    Flashcard("やけます", "burn, be baked, roasted, grilled"),
                    Flashcard("とおります", "pass along a street"),
                    Flashcard("しにます", "die"),
                    Flashcard("びっくりします", "be surprised"),
                    Flashcard("がっかりします", "be disappointed"),
                    Flashcard("あんしんします", "be relieved"),
                    Flashcard("ちこくします", "be late, come late"),
                    Flashcard("そうたいします", "leave (work or school) earlier than usual"),
                    Flashcard("けんかします", "quarrel, fight"),
                    Flashcard("りこんします", "divorce"),
                    Flashcard("ふくざつ[な]", "complicated, complex"),
                    Flashcard("じゃま[な]", "obstructive, in the way"),
                    Flashcard("きたない", "dirty"),
                    Flashcard("うれしい", "happy"),
                    Flashcard("かなしい", "sad"),
                    Flashcard("はずかしい", "embarrassed, ashamed"),
                    Flashcard("じしん", "earthquake"),
                    Flashcard("たいふう", "typhoon"),
                    Flashcard("かじ", "fire"),
                    Flashcard("じこ", "accident"),
                    Flashcard("おみあい", "interview with a view to marriage"),
                    Flashcard("でんわだい", "telephone bill"),
                    Flashcard("～だい", "charge, fare, fee"),
                    Flashcard("フロント", "front desk, reception desk"),
                    Flashcard("～ごうしつ", "room number ~"),
                    Flashcard("あせ", "perspiration"),
                    Flashcard("あせをかきます", "perspire"),
                    Flashcard("タオル", "towel"),
                    Flashcard("せっけん", "soap"),
                    Flashcard("おおぜい", "a great number of people"),
                    Flashcard("おつかれさまでした", "Thank you for your hard work."),
                    Flashcard("うかがいます", "I'm coming."),
                    Flashcard("とちゅうで", "on the way, in the midst of"),
                    Flashcard("トラック", "truck"),
                    Flashcard("ぶつかります", "bump, collide"),
                    Flashcard("ならびます", "stand in a queue, line up"),
                    Flashcard("おとな", "adult"),
                    Flashcard("ようふく", "western clothes"),
                    Flashcard("せいようかします", "be Westernized"),
                    Flashcard("あいます", "fit, suit"),
                    Flashcard("いまでは", "now"),
                    Flashcard("せいじんしき", "coming-of-age celebration")
                )
                40 -> listOf(
                    Flashcard("かぞえます", "count"),
                    Flashcard("はかります", "measure, weigh"),
                    Flashcard("たしかめます", "confirm, make sure"),
                    Flashcard("あいます", "the size fits"),
                    Flashcard("しゅっぱつします", "depart"),
                    Flashcard("とうちゃくします", "arrive"),
                    Flashcard("よいます", "get drunk"),
                    Flashcard("きけん[な]", "dangerous"),
                    Flashcard("ひつよう[な]", "necessary"),
                    Flashcard("うちゅう", "space, universe"),
                    Flashcard("ちきゅう", "earth"),
                    Flashcard("ぼうねんかい", "year-end party"),
                    Flashcard("しんねんかい", "New Year's party"),
                    Flashcard("にじかい", "second party"),
                    Flashcard("たいかい", "mass meeting, convention"),
                    Flashcard("マラソン", "marathon"),
                    Flashcard("コンテスト", "contest"),
                    Flashcard("おもて", "face, front"),
                    Flashcard("うら", "back (side)"),
                    Flashcard("へんじ", "reply"),
                    Flashcard("もうしこみ", "application"),
                    Flashcard("ほんとう", "truth, fact"),
                    Flashcard("まちがい", "mistake"),
                    Flashcard("きず", "defect, wound, scratch"),
                    Flashcard("ズボン", "trousers"),
                    Flashcard("ながさ", "length"),
                    Flashcard("おもさ", "weight"),
                    Flashcard("たかさ", "height"),
                    Flashcard("おおきさ", "size, scale"),
                    Flashcard("～びん", "flight, flight number"),
                    Flashcard("～ごう", "train number, typhoon number, etc."),
                    Flashcard("～こ", "(counter for small objects)"),
                    Flashcard("～ほん", "(counter for long objects)"),
                    Flashcard("～はい", "(counter for full cups, glasses)"),
                    Flashcard("～キロ", "kilograms, kilometers"),
                    Flashcard("～グラム", "grams"),
                    Flashcard("～センチ", "centimeters"),
                    Flashcard("～ミリ", "millimeters"),
                    Flashcard("～いじょう", "not less than ~, over ~"),
                    Flashcard("～いか", "not more than ~, under ~"),
                    Flashcard("どうでしょうか", "How is ~? (polite)"),
                    Flashcard("せいせき", "performance, score, result"),
                    Flashcard("ところで", "by the way"),
                    Flashcard("ようす", "situation, condition, appearance"),
                    Flashcard("じけん", "incident, case"),
                    Flashcard("オートバイ", "motorcycle"),
                    Flashcard("ばくだん", "bomb"),
                    Flashcard("つみます", "load, pile up"),
                    Flashcard("うんてんしゅ", "driver"),
                    Flashcard("はなれた", "remote"),
                    Flashcard("きゅうに", "suddenly"),
                    Flashcard("うごかします", "start, operate, move"),
                    Flashcard("いっしょうけんめい", "with all one's effort"),
                    Flashcard("はんにん", "suspect, criminal"),
                    Flashcard("てにいれます", "obtain, get"),
                    Flashcard("いまでも", "even now"),
                    Flashcard("うわさします", "gossip")
                )
                41 -> listOf(
                    Flashcard("いただきます", "receive (humble)"),
                    Flashcard("くださいます", "give (respectful)"),
                    Flashcard("やります", "give (to juniors, animals, etc.)"),
                    Flashcard("よびます", "invite"),
                    Flashcard("とりかえます", "exchange"),
                    Flashcard("しんせつにします", "be kind to"),
                    Flashcard("かわいい", "lovely, cute"),
                    Flashcard("めずらしい", "rare, uncommon"),
                    Flashcard("おいわい", "celebration, gift"),
                    Flashcard("おとしだま", "New Year's gift money"),
                    Flashcard("おみまい", "expression of sympathy, gift to a sick person"),
                    Flashcard("きょうみ", "interest"),
                    Flashcard("じょうほう", "information"),
                    Flashcard("ぶんぽう", "grammar"),
                    Flashcard("はつおん", "pronunciation"),
                    Flashcard("さる", "ape, monkey"),
                    Flashcard("えさ", "feed, bait"),
                    Flashcard("おもちゃ", "toy"),
                    Flashcard("えほん", "picture book"),
                    Flashcard("えはがき", "picture postcard"),
                    Flashcard("ドライバー", "screwdriver"),
                    Flashcard("ハンカチ", "handkerchief"),
                    Flashcard("くつした", "socks, stockings"),
                    Flashcard("てぶくろ", "gloves"),
                    Flashcard("ゆびわ", "ring"),
                    Flashcard("バッグ", "bag"),
                    Flashcard("そふ", "(my) grandfather"),
                    Flashcard("そぼ", "(my) grandmother"),
                    Flashcard("まご", "(my) grandchild"),
                    Flashcard("おじ", "(my) uncle"),
                    Flashcard("おじさん", "(someone else's) uncle"),
                    Flashcard("おば", "(my) aunt"),
                    Flashcard("おばさん", "(someone else's) aunt"),
                    Flashcard("おととし", "the year before last"),
                    Flashcard("はい", "yes, I see"),
                    Flashcard("もうしわけありません", "I'm sorry. / Excuse me."),
                    Flashcard("あずかります", "keep, receive (a thing) for temporary keeping"),
                    Flashcard("せんじつ", "the other day"),
                    Flashcard("たすかります", "be of help"),
                    Flashcard("むかしばなし", "old tale, folklore"),
                    Flashcard("ある～", "a certain ~, one ~"),
                    Flashcard("おとこ", "man"),
                    Flashcard("こどもたち", "children"),
                    Flashcard("いじめます", "bully, abuse, ill-treat"),
                    Flashcard("かめ", "turtle, tortoise"),
                    Flashcard("たすけます", "save, help"),
                    Flashcard("おしろ", "castle"),
                    Flashcard("おひめさま", "princess"),
                    Flashcard("たのしく", "happily"),
                    Flashcard("くらします", "live, lead a life"),
                    Flashcard("りく", "land, shore"),
                    Flashcard("すると", "and, then"),
                    Flashcard("けむり", "smoke"),
                    Flashcard("まっしろ[な]", "pure white"),
                    Flashcard("なかみ", "content")
                )
                42 -> listOf(
                    Flashcard("つつみます", "wrap"),
                    Flashcard("わかします", "boil"),
                    Flashcard("まぜます", "mix"),
                    Flashcard("けいさんします", "calculate"),
                    Flashcard("ならびます", "stand in a queue, line up"),
                    Flashcard("じょうぶ[な]", "strong, healthy"),
                    Flashcard("アパート", "apartment"),
                    Flashcard("べんごし", "lawyer, attorney"),
                    Flashcard("おんがくか", "musician"),
                    Flashcard("こどもたち", "children"),
                    Flashcard("しぜん", "nature"),
                    Flashcard("きょういく", "education"),
                    Flashcard("ぶんか", "culture"),
                    Flashcard("しゃかい", "society"),
                    Flashcard("せいじ", "politics"),
                    Flashcard("ほうりつ", "law"),
                    Flashcard("せんそう", "war"),
                    Flashcard("へいわ", "peace"),
                    Flashcard("もくてき", "purpose"),
                    Flashcard("ろんぶん", "thesis, academic paper"),
                    Flashcard("たのしみ", "pleasure, enjoyment, expectation"),
                    Flashcard("ミキサー", "mixer, blender"),
                    Flashcard("やかん", "kettle"),
                    Flashcard("せんぬき", "cap opener, bottle opener"),
                    Flashcard("かんきり", "can opener"),
                    Flashcard("かんづめ", "canned food, tinned food"),
                    Flashcard("ふろしき", "wrapping cloth used to carry things"),
                    Flashcard("そろばん", "abacus"),
                    Flashcard("たいおんけい", "(clinical) thermometer"),
                    Flashcard("ざいりょう", "material, ingredient"),
                    Flashcard("ある～", "a certain ~, one ~"),
                    Flashcard("いっしょうけんめい", "with all one's effort"),
                    Flashcard("なぜ", "why"),
                    Flashcard("どのくらい", "how much/many"),
                    Flashcard("こくれん", "United Nations"),
                    Flashcard("でます", "[a bonus] be paid"),
                    Flashcard("ローン", "loan"),
                    Flashcard("セット", "set"),
                    Flashcard("あと", "the rest"),
                    Flashcard("カップラーメン", "instant noodles in a cup"),
                    Flashcard("インスタントラーメン", "instant noodles"),
                    Flashcard("なべ", "pan, pot"),
                    Flashcard("どんぶり", "ceramic bowl"),
                    Flashcard("しょくひん", "food"),
                    Flashcard("ちょうさ", "investigation, survey"),
                    Flashcard("カップ", "cup"),
                    Flashcard("また", "and"),
                    Flashcard("～の かわりに", "in place of ~, instead of ~"),
                    Flashcard("どこででも", "in any place"),
                    Flashcard("いまでは", "now")
                )
                43 -> listOf(
                    Flashcard("ふえます", "increase"),
                    Flashcard("へります", "decrease"),
                    Flashcard("あがります", "rise"),
                    Flashcard("さがります", "fall"),
                    Flashcard("きれます", "break, snap"),
                    Flashcard("とれます", "come off"),
                    Flashcard("おちます", "fall down"),
                    Flashcard("なくなります", "run out, be lost"),
                    Flashcard("じょうぶ[な]", "strong, healthy"),
                    Flashcard("へん[な]", "strange, peculiar"),
                    Flashcard("しあわせ[な]", "happy"),
                    Flashcard("うまい", "tasty, good at"),
                    Flashcard("まずい", "not tasty"),
                    Flashcard("つまらない", "boring, uninteresting"),
                    Flashcard("ガソリン", "petrol, gasoline"),
                    Flashcard("ひ", "fire"),
                    Flashcard("だんぼう", "heating"),
                    Flashcard("れいぼう", "air-conditioning"),
                    Flashcard("センス", "taste, sense"),
                    Flashcard("いまにも", "at any moment"),
                    Flashcard("わあ", "Oh! / Wow!"),
                    Flashcard("かいいん", "member"),
                    Flashcard("てきとう[な]", "suitable, proper"),
                    Flashcard("ねんれい", "age"),
                    Flashcard("しゅうにゅう", "income"),
                    Flashcard("ぴったり", "exactly, just right"),
                    Flashcard("そのうえ", "in addition to that, moreover"),
                    Flashcard("～といいます", "(one’s name) is ~"),
                    Flashcard("ばら", "rose"),
                    Flashcard("ドライブ", "driving")
                )
                44 -> listOf(
                    Flashcard("なきます", "cry"),
                    Flashcard("わらいます", "laugh, smile"),
                    Flashcard("かわきます", "dry"),
                    Flashcard("ぬれます", "get wet"),
                    Flashcard("すべります", "slip"),
                    Flashcard("おきます", "[an accident] happen"),
                    Flashcard("ちょうせつします", "adjust"),
                    Flashcard("あんぜん[な]", "safe"),
                    Flashcard("ていねい[な]", "polite, courteous, careful"),
                    Flashcard("こまかい", "small, fine"),
                    Flashcard("こい", "strong (taste), dark (color)"),
                    Flashcard("うすい", "weak (taste), light (color)"),
                    Flashcard("くうき", "air"),
                    Flashcard("なみだ", "tear"),
                    Flashcard("わしょく", "Japanese dish"),
                    Flashcard("ようしょく", "Western dish"),
                    Flashcard("おかず", "side dish"),
                    Flashcard("りょう", "quantity"),
                    Flashcard("～ばい", "~ times"),
                    Flashcard("はんぶん", "half"),
                    Flashcard("シングル", "single room"),
                    Flashcard("ツイン", "twin-bedded room"),
                    Flashcard("たんす", "chest of drawers"),
                    Flashcard("せんたくもの", "washing, laundry"),
                    Flashcard("りゆう", "reason"),
                    Flashcard("どうなさいますか", "What can I do for you?"),
                    Flashcard("カット", "haircut"),
                    Flashcard("シャンプー", "shampoo"),
                    Flashcard("どういうふうになさいますか", "How would you like it done?"),
                    Flashcard("ショート", "short"),
                    Flashcard("～みたいにしてください", "Do it like ~."),
                    Flashcard("これでよろしいでしょうか", "Would this be all right?"),
                    Flashcard("おつかれさまでした", "Thank you for your patience."),
                    Flashcard("いやがります", "dislike"),
                    Flashcard("また", "and"),
                    Flashcard("じゅんじょ", "order"),
                    Flashcard("ひょうげん", "expression"),
                    Flashcard("たとえば", "for example"),
                    Flashcard("わかれます", "part, separate"),
                    Flashcard("これら", "these things"),
                    Flashcard("えんぎがわるい", "unlucky, ill-omened")
                )
                45 -> listOf(
                    Flashcard("あやまります", "apologize"),
                    Flashcard("あいます", "encounter [an accident]"),
                    Flashcard("しんじます", "believe, trust"),
                    Flashcard("よういします", "prepare"),
                    Flashcard("キャンセルします", "cancel"),
                    Flashcard("うまく いきます", "go well"),
                    Flashcard("ほしょうしょ", "guarantee"),
                    Flashcard("りょうしゅうしょ", "receipt"),
                    Flashcard("おくりもの", "gift, present"),
                    Flashcard("まちがいでんわ", "wrong (telephone) number"),
                    Flashcard("キャンプ", "camp"),
                    Flashcard("かかり", "person in charge"),
                    Flashcard("ちゅうし", "calling off, cancelling, suspension"),
                    Flashcard("てん", "point, score"),
                    Flashcard("レバー", "lever"),
                    Flashcard("～えんさつ", "[-yen] note, bill"),
                    Flashcard("ちゃんと", "regularly, properly"),
                    Flashcard("きゅうに", "suddenly"),
                    Flashcard("たのしみにしています", "be looking forward to, be expecting"),
                    Flashcard("いじょうです", "That's all."),
                    Flashcard("かかりいん", "person in charge, attendant"),
                    Flashcard("コース", "course"),
                    Flashcard("スタート", "start"),
                    Flashcard("～い", "-th ranking"),
                    Flashcard("ゆうしょうします", "win the championship"),
                    Flashcard("なやみ", "trouble, worry"),
                    Flashcard("めざましどけい", "alarm clock"),
                    Flashcard("ねむります", "sleep"),
                    Flashcard("めがさめます", "wake up"),
                    Flashcard("だいがくせい", "university student"),
                    Flashcard("かいとう", "answer, reply"),
                    Flashcard("なります", "ring"),
                    Flashcard("セットします", "set"),
                    Flashcard("それでも", "nevertheless, for all that")
                )
                46 -> listOf(
                    Flashcard("やきます", "bake, grill, roast"),
                    Flashcard("わたします", "hand over"),
                    Flashcard("かえってきます", "come back"),
                    Flashcard("でます", "[a bus] leave, depart"),
                    Flashcard("るす", "absence"),
                    Flashcard("たくはいびん", "delivery service"),
                    Flashcard("げんいん", "cause"),
                    Flashcard("ちゅうしゃ", "injection"),
                    Flashcard("しょくよく", "appetite"),
                    Flashcard("パンフレット", "pamphlet"),
                    Flashcard("ステレオ", "stereo"),
                    Flashcard("こちら", "my place, my side"),
                    Flashcard("～のところ", "the place around ~"),
                    Flashcard("ちょうど", "just, exactly"),
                    Flashcard("たったいま", "just now"),
                    Flashcard("いまいいでしょうか", "May I bother you now?"),
                    Flashcard("ガスサービスセンター", "gas service center"),
                    Flashcard("ガスレンジ", "gas range, gas cooker"),
                    Flashcard("ぐあい", "condition"),
                    Flashcard("どちらさまでしょうか", "Who is this, please?"),
                    Flashcard("むかいます", "head for"),
                    Flashcard("おまたせしました", "Sorry to have kept you waiting."),
                    Flashcard("ちしき", "knowledge"),
                    Flashcard("ほうこ", "treasury"),
                    Flashcard("てにはいります", "[information] come in, reach"),
                    Flashcard("システム", "system"),
                    Flashcard("たとえば", "for example"),
                    Flashcard("キーワード", "key word"),
                    Flashcard("いちぶぶん", "one part"),
                    Flashcard("にゅうりょくします", "input"),
                    Flashcard("びょう", "second"),
                    Flashcard("でます", "[a book] be published")
                )
                47 -> listOf(
                    Flashcard("あつまります", "[people] gather"),
                    Flashcard("わかれます", "[people] part, separate"),
                    Flashcard("ながいきします", "live long"),
                    Flashcard("します", "[sound/voice] be heard, [taste] be tasted, [smell] be smelled"),
                    Flashcard("さします", "put up [an umbrella]"),
                    Flashcard("ひどい", "terrible, severe, cruel"),
                    Flashcard("こわい", "frightening, horrible"),
                    Flashcard("てんきよほう", "weather forecast"),
                    Flashcard("はっぴょう", "announcement, presentation"),
                    Flashcard("じっけん", "experiment"),
                    Flashcard("じんこう", "population"),
                    Flashcard("におい", "smell"),
                    Flashcard("かがく", "science"),
                    Flashcard("いがく", "medicine, medical science"),
                    Flashcard("ぶんがく", "literature"),
                    Flashcard("パトカー", "patrol car"),
                    Flashcard("きゅうきゅうしゃ", "ambulance"),
                    Flashcard("さんせい", "approval, agreement"),
                    Flashcard("はんたい", "objection, opposition"),
                    Flashcard("だんせい", "male, man"),
                    Flashcard("じょせい", "female, woman"),
                    Flashcard("どうも", "it appears that (tentative judgement)"),
                    Flashcard("～によると", "according to ~"),
                    Flashcard("こいびと", "sweetheart, boyfriend, girlfriend"),
                    Flashcard("こんやくします", "get engaged"),
                    Flashcard("あいて", "the other person"),
                    Flashcard("しりあいます", "get acquainted"),
                    Flashcard("へいきんじゅみょう", "average life span"),
                    Flashcard("くらべます", "compare"),
                    Flashcard("はかせ", "doctor (PhD)"),
                    Flashcard("のう", "brain"),
                    Flashcard("ホルモン", "hormone"),
                    Flashcard("けしょうひん", "cosmetics"),
                    Flashcard("しらべ", "survey, research"),
                    Flashcard("けしょう", "makeup")
                )
                48 -> listOf(
                    Flashcard("おろします", "put down, lower, unload"),
                    Flashcard("とどけます", "deliver"),
                    Flashcard("せわをします", "take care of"),
                    Flashcard("ろくおんします", "record"),
                    Flashcard("いや[な]", "unwilling, reluctant"),
                    Flashcard("じゅく", "cram school"),
                    Flashcard("せいと", "pupil"),
                    Flashcard("ファイル", "file"),
                    Flashcard("じゆうに", "freely"),
                    Flashcard("～かん", "for ~ (duration)"),
                    Flashcard("いいことですね", "That's good."),
                    Flashcard("おいそがしいですか", "Are you busy? (respectful)"),
                    Flashcard("えいぎょう", "business, sales"),
                    Flashcard("それまでに", "by that time"),
                    Flashcard("かまいません", "It’s all right. / I don’t mind."),
                    Flashcard("たのしみます", "enjoy oneself"),
                    Flashcard("おや", "parent"),
                    Flashcard("しょうがくせい", "elementary school child"),
                    Flashcard("～パーセント", "~ percent"),
                    Flashcard("そのつぎ", "next"),
                    Flashcard("しゅうじ", "calligraphy"),
                    Flashcard("ふつうの", "normal, usual")
                )
                49 -> listOf(
                    Flashcard("つとめます", "work [for a company]"),
                    Flashcard("やすみます", "go to bed, sleep"),
                    Flashcard("かけます", "sit on [a chair]"),
                    Flashcard("すごします", "spend (time), pass (time)"),
                    Flashcard("よります", "drop into [a bank]"),
                    Flashcard("いらっしゃいます", "be, go, come (respectful)"),
                    Flashcard("めしあがります", "eat, drink (respectful)"),
                    Flashcard("おっしゃいます", "say (respectful)"),
                    Flashcard("なさいます", "do (respectful)"),
                    Flashcard("ごらんになります", "see, look at (respectful)"),
                    Flashcard("ごぞんじです", "know (respectful)"),
                    Flashcard("あいさつ", "greeting, address"),
                    Flashcard("はいざら", "ashtray"),
                    Flashcard("りょかん", "Japanese-style hotel or inn"),
                    Flashcard("かいじょう", "meeting place, hall"),
                    Flashcard("バスてい", "bus stop"),
                    Flashcard("ぼうえき", "trade"),
                    Flashcard("～さま", "Mr., Ms. (respectful)"),
                    Flashcard("かえりに", "on the way back"),
                    Flashcard("たまに", "once in a while"),
                    Flashcard("ちっとも", "not at all (with negatives)"),
                    Flashcard("えんりょなく", "without reserve, without hesitation"),
                    Flashcard("～ねん～くみ", "class ~ of ~th grade"),
                    Flashcard("では", "well, then (polite)"),
                    Flashcard("だします", "run [a fever]"),
                    Flashcard("よろしくおつたえください", "Give my best regards."),
                    Flashcard("しつれいいたします", "Goodbye (humble)"),
                    Flashcard("こうし", "lecturer"),
                    Flashcard("おおくの～", "many ~, much ~"),
                    Flashcard("さくひん", "work (of art, etc.)"),
                    Flashcard("じゅしょうします", "be awarded a prize"),
                    Flashcard("せかいてきに", "worldwide"),
                    Flashcard("さッカ", "novelist, writer"),
                    Flashcard("～でいらっしゃいます", "(respectful of です)"),
                    Flashcard("ちょうなん", "one's eldest son"),
                    Flashcard("しょうがい", "handicap, defect"),
                    Flashcard("おもちです", "have (respectful)"),
                    Flashcard("さっきょく", "composition (music)"),
                    Flashcard("かつどう", "activity"),
                    Flashcard("それでは", "well, so (indicating end or beginning)")
                )
                50 -> listOf(
                    Flashcard("まいります", "go, come (humble)"),
                    Flashcard("おります", "be (humble)"),
                    Flashcard("いただきます", "eat, drink, receive (humble)"),
                    Flashcard("もうします", "say (humble)"),
                    Flashcard("いたします", "do (humble)"),
                    Flashcard("はいけんします", "see, look at (humble)"),
                    Flashcard("ぞんじます", "know (humble)"),
                    Flashcard("うかがいます", "ask, hear, visit (humble)"),
                    Flashcard("おめにかかります", "meet (humble)"),
                    Flashcard("ございます", "be (polite of あります)"),
                    Flashcard("～でございます", "be (polite of です)"),
                    Flashcard("わたくし", "I (humble)"),
                    Flashcard("ガイド", "guide"),
                    Flashcard("おたく", "someone else's house"),
                    Flashcard("こうがい", "suburbs"),
                    Flashcard("アルバム", "album"),
                    Flashcard("さらいしゅう", "the week after next"),
                    Flashcard("さらいげつ", "the month after next"),
                    Flashcard("さらいねん", "the year after next"),
                    Flashcard("はんとし", "half a year"),
                    Flashcard("さいしょに", "first of all"),
                    Flashcard("さいごに", "lastly"),
                    Flashcard("ただいま", "now"),
                    Flashcard("きんちょうします", "become tense, be strained, be nervous"),
                    Flashcard("ほうそうします", "broadcast"),
                    Flashcard("とります", "record [video]"),
                    Flashcard("しょうきん", "prize money"),
                    Flashcard("しぜん", "nature"),
                    Flashcard("きりん", "giraffe"),
                    Flashcard("ぞう", "elephant"),
                    Flashcard("ころ", "times, days"),
                    Flashcard("かないます", "[a dream] be realized, come true"),
                    Flashcard("ひとことよろしいでしょうか", "May I say one word?"),
                    Flashcard("きょうりょくします", "cooperate"),
                    Flashcard("こころから", "from my heart, sincerely"),
                    Flashcard("かんしゃします", "be grateful, be thankful"),
                    Flashcard("おれい", "gratitude, thanks"),
                    Flashcard("はいけい", "Dear ~"),
                    Flashcard("うつくしい", "beautiful"),
                    Flashcard("いかがおすごしでしょうか", "How are you getting along? (respectful)"),
                    Flashcard("めいわくをかけます", "trouble, annoy, inconvenience"),
                    Flashcard("いかします", "make good use of"),
                    Flashcard("おしろ", "castle"),
                    Flashcard("けいぐ", "Sincerely yours,")
                )
                else -> emptyList()
            }
        )
    }
}

// Helper function to get a specific lesson's flashcards
fun getN4FlashcardSet(id: String): FlashcardSet? {
    return getAllN4FlashcardSets().find { it.id == id }
}
